### ISSUE TITLE
Variables overiding if used keyrune in same project

### ISSUE THREAD

**Issue by JayGray** [andrewgioia/Mana#1]
If I use https://github.com/andrewgioia/keyrune and https://github.com/andrewgioia/Mana in the same project the variables are overiding each other.

A prefix could be helpfull here eg: 
Instead of
```less
@font-path: '../fonts';
@version: '0.1';
@font-size-base: 14px;
@prefix: ms;
@serif-font: 'MPlantin, Garamond, Palatino, 'Times New Roman', Times, serif';
```
do
```less
@ms-font-path: '../fonts';
@ms-version: '0.1';
@ms-font-size-base: 14px;
@ms-prefix: ms;
@ms-serif-font: 'MPlantin, Garamond, Palatino, 'Times New Roman', Times, serif';
```

**Comment by andrewgioia** [comment]
Excellent idea, I'll add this to the next version of both and should have that up early this week.
