### ISSUE TITLE
[Request] Battle card loyalty box and MTGO counter

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#103]
Hi Andrew, the new Battle card type has been revealed and it has it's own unique property: Defense.
Similar to Planeswalker loyalty in placement and effect, it has a number inside representing the number of defense counters on the Battle. It's also depleted by damage (both combat and spell).
![Defense](https://user-images.githubusercontent.com/128204978/232199016-b0f884c3-6c0b-4e7c-bf67-ae12c9b3439e.png)

In use on a physical Battle card:
![mom-194-invasion-of-zendikar](https://user-images.githubusercontent.com/128204978/228444148-106b756e-3e44-45e4-9599-451a22510f2b.png)

In use on MTGO:
![MTGO_Battle_in-play](https://github.com/andrewgioia/mana/assets/128204978/c2109a0e-bfa0-4a90-9269-78e2fe29ddd1)

**Comment by andrewgioia** [comment]
Added in 1.15.6
