### ISSUE TITLE
Enrage ability modified and Damage "counter"

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#104]
Hi Andrew, it looks like the MTG Arena icon for Enrage has been modified.

![MTGA_Enrage](https://user-images.githubusercontent.com/128204978/228444847-a679c2e1-81bf-4ccd-961a-53f8338bbfea.png)
It's now two crossed claw marks, rather than just one.

The old Enrage icon has been repurposed into the icon used to indicate damage has been marked on a creature.
![MTGA_Damaged](https://user-images.githubusercontent.com/128204978/228445109-2d60522e-8e44-4b67-ad5d-ada75a94dde9.png)

**Comment by andrewgioia** [comment]
Added and changed in 1.15.6
