### ISSUE TITLE
[Set Release] March of the Machine roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#105]
Hi, just putting a roundup of the new and updated symbols courtesy of the March of the Machine release.

**Card Symbols:**
MOM introduces the Battle card type and brings two new symbols with it.
- Defense (and defense counters) are listed in #103. I think this is going to need both a borderless version and a bordered version for the Magic Online Counters - the same treatment as Planeswalker loyalty.
- The new Future Sight style card symbol is crossed swords.
![Battle](https://user-images.githubusercontent.com/128204978/232202608-fd084a1c-cf21-4c24-9546-be03d204df9e.png)

**Card Subtype Symbols:**
I'm not quite sure where this one should go. MTG Arena has a symbol used to denote Battle - Siege cards but it's not a symbol used anywhere on the card and there aren't any equivalents in the existing symbol set.
![MTGA_Siege](https://user-images.githubusercontent.com/128204978/232203115-1830a314-e30c-4b28-9f02-f0407e0df4fb.png)

**Arena Ability Symbols:**
MOM has two new keyword abilities and one revised ability symbol.
- Backup puts a +1/+1 counter on a creature then gives it the abilities of the Backup creature.
![MTGA_Backup](https://user-images.githubusercontent.com/128204978/232202740-597882ba-7f59-4faf-97d9-46bfa26f8268.png)
- Incubate creates a DFC Incubator token with N +1/+1 counters on it.
![MTGA_Incubate](https://user-images.githubusercontent.com/128204978/232202851-2931719b-b588-4b4b-9409-e92dedc2bf14.png)
- The symbol for Convoke was redesigned. It's no longer the Selesnya guild symbol.
![MTGA_Convoke_MOM](https://user-images.githubusercontent.com/128204978/232202838-65f7572e-2eda-481e-a57c-e2152ec600cb.png)

**Comment by andrewgioia** [comment]
Thanks so much @RivalRowan for this and your other issues!

Just one question: is the crossed swords symbol for the Battle card type, and if so could you let me know where you found that? Just making sure I have it correct.

**Comment by RivalRowan** [comment]
> the crossed swords symbol for the Battle card type, and if so could you let me know where you found that?

@andrewgioia - No worries. The icon is for the Battle card type and is from the Advanced Filters tab in the Deck Construction/Collection window on MTG Arena. The rest of the icons used in that tab are the Future Sight card type icons and so my assumption is that the crossed swords are being used for the same purpose.

![MTGA_Advanced Filters](https://github.com/andrewgioia/mana/assets/128204978/bd8ceab2-2cb5-4115-a8fa-9c7b844ac727)

**Comment by andrewgioia** [comment]
Thanks @RivalRowan! This is extremely helpful.

Kind of odd that the two digital teams don't coordinate this.

**Comment by RivalRowan** [comment]
I just find it odd that MTGO uses a _sideways_ Defense counter. It's not even the correct version of that counter.

**Comment by andrewgioia** [comment]
Thanks again @RivalRowan these are all now added in 1.15.6.
