### ISSUE TITLE
[Ability] Shadow

### ISSUE THREAD

**Issue by RebeccaStevens** [andrewgioia/mana#106]
I'm not sure if there is an official released icon for this yet, but shadow counters are coming in the Doctor Who Commander set.

**Comment by andrewgioia** [comment]
Thanks @RebeccaStevens, I don't see any official symbol in Arena but could check the client assets to see if they added it there. If not we'll have to wait for the client to be updated for this set.

**Comment by andrewgioia** [comment]
Yeah it doesn't look like they ever made one, not even as a punch out counter on the physical Masters of Evil deck.
