### ISSUE TITLE
[Set Release] The Lord of the Rings: Tales of Middle-Earth roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#107]
Hi, just putting a roundup of the new and updated symbols courtesy of the The Lord of the Rings: Tales of Middle-Earth release.

**Arena Ability Symbols:**
LTR has two new keyword abilities.

- The Ring Tempts You is the main feature of the set and gives you an emblem (The Ring) and allows you to designate one of your creatures as your Ring-bearer.
![MTGA_The_Ring_Tempts_You](https://github.com/andrewgioia/mana/assets/128204978/bf1f4eed-0f6b-4bf9-a0a8-6b2b90bcdea4)

- Amass returns as a mechanic but has been modified. Instead of always creating a Zombie Army token, it now creates an Army token of the creature type designated after amass. For LTR the creature type is Orc. The ability icon for Amass Orcs (below) is new. The previous amass icon is still being used for Amass Zombies.
![MTGA_Amass_Orcs](https://github.com/andrewgioia/mana/assets/128204978/a2092cd6-a36d-48a6-ba81-ee0aa686cfd0)

**Designation Symbols:**

- LTR introduces the first Arena creature designation symbol -  Ring-bearer.
![MTGA_Ring-bearer_designation](https://github.com/andrewgioia/mana/assets/128204978/4b21ed40-3898-4846-8046-fe361e0f8a0e)

**Comment by andrewgioia** [comment]
`.ability-the-ring-tempts-you`:

<img src="https://github.com/andrewgioia/mana/assets/221473/a08dcbaf-f9a9-4306-984f-100b3f44208b" width="118">

**Comment by andrewgioia** [comment]
`.ability-amass-orcs`:

<img src="https://github.com/andrewgioia/mana/assets/221473/f4cb51b0-eeb6-4f18-9a6d-bc5d85869ac3" width="88">

**Comment by andrewgioia** [comment]
`.ability-ring-bearer`:

<img src="https://github.com/andrewgioia/mana/assets/221473/e411894c-1bb5-49cc-9bad-5bf399b3bc79" width="72">

**Comment by andrewgioia** [comment]
All added in v1.15.8
