### ISSUE TITLE
[Ability] Improvise

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/mana#108]
Not sure when this was released or why it may have been left out but here it is!

<img width="67" alt="ability-improvise" src="https://github.com/andrewgioia/mana/assets/221473/675ef04b-ecab-4cab-a839-aa96a0a1ef12">

**Comment by RivalRowan** [comment]
Background free version is attached:
![MTGA_Improvise](https://github.com/andrewgioia/mana/assets/128204978/d1230fb8-106b-4664-879c-15e9a4e25b04)

**Comment by andrewgioia** [comment]
`.ability-improvise`:

<img src="https://github.com/andrewgioia/mana/assets/221473/f6025a46-6084-424c-bad8-ab93bdf027e8" width="130">

**Comment by andrewgioia** [comment]
Added in v1.15.8
