### ISSUE TITLE
[Counter] Void counter - MTGO

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#109]
Hi Andrew,
I've come across a Magic Online Counter icon not currently in Mana. It's used for the Void counters from [Dauthi Voidwalker](https://scryfall.com/card/mh2/81/dauthi-voidwalker) but as the symbol is an eye, I assume that's not what the counter is actually named for.

![Void](https://github.com/andrewgioia/mana/assets/128204978/777dc2da-3276-4d41-8782-6ccb180cd70b)

I haven't been able to find the counter's origin yet, nor a good high res version of the icon.
![void counter](https://github.com/andrewgioia/mana/assets/128204978/ed3d6b80-0dcc-4471-a25a-1d101301971d)

**Comment by andrewgioia** [comment]
Added in v1.15.9
