### ISSUE TITLE
[Set Release] Wilds of Eldraine roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#111]
Hi, just putting a roundup of the new and updated symbols courtesy of the Wilds of Eldraine release.

**Arena Ability Symbols:**
WOE has one new keyword ability and one new ability word.
- Bargain is a Kicker variant that lets you sacrifice an artifact, enchantment or token for a bonus effect.
![MTGA_ Bargain](https://github.com/andrewgioia/mana/assets/128204978/3fd136d2-2a9d-4b79-99c2-b7c093f4f9dc)

- Celebration is an ability word that triggers if two or more nonland permanents entered the battlefield under your control this turn.
![MTGA_Celebration](https://github.com/andrewgioia/mana/assets/128204978/63255363-d774-4fae-b33f-072094abc973)

**Role Tokens:**
Roles are new predefined Aura tokens. Each Role has a unique effect when it enchants a creature and along with that MTGA has a unique icon for each one.
![MTGA_Role_Cursed](https://github.com/andrewgioia/mana/assets/128204978/bfded9a3-0b91-4869-88dd-82ae53b1e847) - Cursed
![MTGA_ Role_Monster](https://github.com/andrewgioia/mana/assets/128204978/ad55a323-9565-48cc-b1b8-4b8e13f94d8f) - Monster
![MTGA_Role_Royal](https://github.com/andrewgioia/mana/assets/128204978/3d643b84-a498-4439-a1aa-e7b433cf586d) - Royal
![MTGA_ Role_Sorcery](https://github.com/andrewgioia/mana/assets/128204978/101f7eb5-6528-49b4-956b-f2d3e395184f) - Sorcery
![MTGA_ Role_Wicked](https://github.com/andrewgioia/mana/assets/128204978/4515f3bd-b5e7-45cc-8f61-b96d7323be14) - Wicked
![MTGA_ Role_YoungHero](https://github.com/andrewgioia/mana/assets/128204978/f517972b-c1ec-4be0-aeb0-5434fd331997) - Young Hero

**Comment by andrewgioia** [comment]
Thanks @RivalRowan you're a hero as always, huge help getting these for me.

Will go into 1.15.9 as soon as I can get them all traced/cleaned/added.

**Comment by andrewgioia** [comment]
It looks like [Ellivere of the Wild Court](https://scryfall.com/card/woc/2/ellivere-of-the-wild-court) has a seventh "Virtuous Role" token but since that's not implemented on Arena there is no symbol for it yet.

**Comment by andrewgioia** [comment]
Added in v1.15.9

**Comment by nickmatu** [comment]
Were these icons removed intentionally from v1.16.0 and the master?

**Comment by andrewgioia** [comment]
They’re in the master (v1.15.9 is just a tag on that branch) but I need to merge that into 1.16.0 still. Thats still a WIP in general.
