### ISSUE TITLE
[MTGA] Single card icons - Haktos & Robber of the Rich

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#112]
Hi Andrew,
      I'm not sure where these should go in the Mana set, or even if they belong there. Arena has two card-specific symbols. Both symbols are white, so sorry if they don't seem obvious below.

- Haktos the Unscarred has a unique symbol to indicate his Achilles' heel mana value.
![Icon_Keyword_Haktos png-CAB_25ce752f51bc2594689e54e770a6b622-491389127253917164](https://github.com/andrewgioia/mana/assets/128204978/bd8e97a1-3498-4f95-b4a4-dd3dcc16200e)

- Robber of the Rich has a unique marker for cards exiled with it.
![Qualification_Icon_MayPlay_RobberRich png-CAB_9dc10ff608b57641bd2feecf6ada3147--4088101459412838085](https://github.com/andrewgioia/mana/assets/128204978/fef278f6-0429-4b43-a5fb-b87fcf791b4b)

**Comment by andrewgioia** [comment]
Added in v1.15.9
