### ISSUE TITLE
[Watermark] trumpkatsumai

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/mana#114]
The watermark `trumpkatsumi` appears on [two cards](https://scryfall.com/search?q=watermark%253Atrumpkatsumai) that were media inserts in a Japanese magazine.

I can't find the logo anywhere and the card scans don't provide an easy way to trace the foil watermark.

If anyone is able to provide a decent source for the logo or the watermark I can add this and get one step closer to 100% on the watermarks.

**Comment by 4eveRS** [comment]
Hello @andrewgioia,

I did some research and found a the logo for this watermark, it's not perfect as it's taken from a manga scan.

![trumpkatsumi ](https://github.com/andrewgioia/mana/assets/4212200/65af065f-380a-4bb4-89fe-046f4d7a446b)

Image was taken from this website: https://books.rakuten.co.jp/rb/16643999/

**Comment by andrewgioia** [comment]
Amazing find @4eveRS! This should be more than enough to trace reliably. Thanks so much for this!

**Comment by 4eveRS** [comment]
Glad to help and looking forward for the new watermarks!
