### ISSUE TITLE
[Set Release] The Lost Caverns of Ixalan roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#117]
Hi, just putting a roundup of the new symbols courtesy of The Lost Caverns of Ixalan (LCI) release.
For the first time, WotC has published a full [Arena Release Notes](https://magic.wizards.com/en/news/mtg-arena/mtg-arena-release-notes-the-lost-caverns-of-ixalan) article so most of the symbols can be found there.

**Arena Ability Symbols:**
LCI has one new keyword ability, two new keyword actions and two new ability words.

![icon_keyword_craft](https://github.com/andrewgioia/mana/assets/128204978/cfd3dcf7-8a09-4461-ba46-04a10674f580) - [Craft](https://mtg.fandom.com/wiki/Craft) is an activated ability that lets you transform a permanent by paying mana and exiling one or more cards of a certain quality (from either the battlefield or the graveyard). The bottom part of the spanner is cut off in this image but not in-game.

![icon_keyword_discover](https://github.com/andrewgioia/mana/assets/128204978/140a4622-22c1-4bae-ad83-11c238d389cc) - [Discover](https://mtg.fandom.com/wiki/Discover) is a keyword action that acts as a fixed version of [Cascade](https://mtg.fandom.com/wiki/Cascade). You exile cards from the top of your library until you hit a card with mana value less than or equal to the discover number. You may cast that card and the rest go to the bottom of your library in a random order.

![icon_keyword_descend](https://github.com/andrewgioia/mana/assets/128204978/88b37362-0b02-4be3-9c5f-c49055b3972d)![Icon_Keyword_Descend_Active png-CAB_97e9ef01098a3b3006ab7fb8495365fa-6140232382847824910](https://github.com/andrewgioia/mana/assets/128204978/315d6780-2724-448e-9323-2c0e7707d2a5) - [Descended](https://mtg.fandom.com/wiki/Descend) is a bit of a headache because it's four different things being used in two different ways. You've got:
- Descended - This is the keyword action (or maybe player designation) and means "A permanent card went to your graveyard this turn from anywhere". It's used to trigger abilities and effects.
![Descend_example1](https://github.com/andrewgioia/mana/assets/128204978/552ff1e9-69b6-47fc-a966-022b83f701dd)
- _Descend 4_ and _Descend 8_ - both of these can be thought of as [Threshold](https://mtg.fandom.com/wiki/Threshold) or [Delirium](https://mtg.fandom.com/wiki/Delirium) variants. If you have four or eight permanent cards in your graveyard you get a bonus effect (or a bigger effect). They are both ability words.
![Descend_example2](https://github.com/andrewgioia/mana/assets/128204978/5898daa2-9bf8-4bcb-86e4-7ea1276d794b)
- _Fathomless Decent_ - this is another ability word that just means the effect gets bigger the more permanent cards are in the graveyard. Unlike the other three, this one scales with graveyard size.
![Descend_example3](https://github.com/andrewgioia/mana/assets/128204978/5978f871-ab17-48f2-be5d-05c78bc05fb6)

For the purposes of Mana, the pick-axe icon is used for both cards with descended effects and cards with _Fathomless descent_. With _Fathomless descent_ it also gets a numeric counter, to indicate the size of the descent.

**Arena Exclusive Counters:**
LCI introduces a number of new counters to Arena but only one of them is receiving a counter symbol - **Finality** counters.
Finality counters have rules baggage, so when a permanent with a finality counter on it dies, it's exiled instead.

![Icon_Keyword_Finality png-CAB_97e9ef01098a3b3006ab7fb8495365fa-657922842557569684](https://github.com/andrewgioia/mana/assets/128204978/52872feb-b9fe-400d-a726-0a9734c00e33)![glass_counter_Finality png-CAB_719b4cd1ee4b87d91a1cb8058888111e--7372102997939771364](https://github.com/andrewgioia/mana/assets/128204978/1b329b7b-4662-4b88-817e-383c52dcfcf9)

As noted in #116, Arena is using the same symbol for Finality counters as the physical punch-out cards. MTGO should be using the same symbol but we won't know until the set is released.

**Misc:**
The set also reuses [Explore](https://mtg.fandom.com/wiki/Explore) and [Stun counters](https://mtg.fandom.com/wiki/Stun_counter), but there doesn't appear to be any changes in those icon from their last uses.

**Comment by andrewgioia** [comment]
Added in v1.17.0!
