### ISSUE TITLE
[MKM] Ravnica Agency symbol(s)

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#118]
Hi Andrew,
Murders at Karlov Manor introduces the [Ravnican Agency of Magicological Investigations](https://mtg.fandom.com/wiki/Ravnican_Agency_of_Magicological_Investigations) (RAMI) as a major factor keeping the peace between the guilds post-New Phyrexia's invasion. The RAMI has it's own unique identity badge, seen on Kellan, [Hotshot Investigators](https://scryfall.com/card/mkm/60/hotshot-investigators), [Novice Inspector](https://scryfall.com/card/mkm/29/novice-inspector), the victim of [Shock](https://scryfall.com/card/mkm/144/shock) and Alquist Proft on the [booster box](https://wpn.wizards.com/en/products/murders-at-karlov-manor?product=5SizhhA6R6eYtciug48Ggr) and [bundle](https://wpn.wizards.com/en/products/murders-at-karlov-manor?product=1eV7QUsmBklYOW9Ubkddvu) packages.

The symbol is a stylized eye underneath a building entrance with five arches.
Source: [Murders At Karlov Manor Debut Aftershow](https://www.youtube.com/watch?v=mPYIidIMzyc)
The below image is also used as the punch-out "solved" indicator for tabletop gameplay. Arena uses a different symbol (see #121) for the same purpose.
![Solved](https://github.com/andrewgioia/mana/assets/128204978/012b68c0-1e74-4519-9de6-af25c2e5aaae)

The below Beadle & Grimm's images are from an officially licensed product.
Source: [Murders at Karlov Manor: The Case of the Three Blade Knife - Beadle & Grimm's](https://beadleandgrimms.com/products/murders-at-karlov-manor-the-case-of-the-three-blade-knife-mtg)
![RAMI_badge_raised_Beadle-Grimms](https://github.com/andrewgioia/mana/assets/128204978/edd03ffb-293f-4b94-bde8-0170b05acb78)

![RAMI_badge_Beadle-Grimms](https://github.com/andrewgioia/mana/assets/128204978/a2844e34-591c-4341-9fe2-a4cf0a73ee75)

**Comment by andrewgioia** [comment]
Added in v1.17.0!
