### ISSUE TITLE
[MTGA] Power & Toughness icons

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#119]
MTG arena has custom icons for power and toughness.

![Captura de tela 2023-12-14 151954](https://github.com/andrewgioia/mana/assets/4212200/ba2fc2bd-b999-4eaf-824a-d9c3cc92ff44)

**Comment by RivalRowan** [comment]
Here are the individual symbols:
![NPE_icon_power png-CAB_850bdfd675790496694da658aba3c900--6060440312329537164](https://github.com/andrewgioia/mana/assets/128204978/037dd2c0-fdcb-487e-a5ef-781cfe95d1d6) ![NPE_icon_toughness png-CAB_850bdfd675790496694da658aba3c900-6359718355728967930](https://github.com/andrewgioia/mana/assets/128204978/56712010-14e0-4575-9367-b4007719b635)

I'm pretty sure they only appear in the new player on-boarding experience.
