### ISSUE TITLE
[Set Release] Khans of Tarkir - MTGA roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#120]
Hi, just putting a roundup of the new symbols courtesy of the Khans of Tarkir (KTK) set release.

WotC have added the [whole set](https://mtg.fandom.com/wiki/Khans_of_Tarkir#MTG_Arena) (not the block) to Arena to help transition the Explorer format closer to tournament legal paper Pioneer. Each of the new clan mechanics in the set has received an ability symbol (Raid and Prowess already exist on Arena). The Morph mechanic has also received a symbol.

**Arena Ability Symbols:**
![MTGA_Delve](https://github.com/andrewgioia/mana/assets/128204978/d194bd12-09de-4e48-97f7-9f1c0f88be91) - [Delve](https://mtg.fandom.com/wiki/Delve)

![MTGA_Ferocious](https://github.com/andrewgioia/mana/assets/128204978/1621cd0b-e1db-4f3a-a8bb-8c922cebed06) - [Ferocious](https://mtg.fandom.com/wiki/Ferocious)

![MTGA_Outlast](https://github.com/andrewgioia/mana/assets/128204978/5a6d2bd8-81cd-44d3-990a-6951edd8f03a) - [Outlast](https://mtg.fandom.com/wiki/Outlast)

![MTGA_Morph](https://github.com/andrewgioia/mana/assets/128204978/f502a17b-e14e-483d-8037-6bcd2c2d2dc8) - [Morph](https://mtg.fandom.com/wiki/Morph)

**Misc:**
As previously mentioned, [Prowess](https://mtg.fandom.com/wiki/Prowess) and [Raid](https://mtg.fandom.com/wiki/Raid), are included in the set but there doesn't appear to be any changes in those icon from their last uses.

[Personally, I prefer the Onslaught morph shell.]

**Comment by andrewgioia** [comment]
Added in v1.17.0!
