### ISSUE TITLE
[Set Release] Murders at Karlov Manor roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#121]
Hi @andrewgioia, just putting a roundup of the new symbols courtesy of the Murders at Karlov Manor (MKM) release.

**Arena Ability Symbols:**
MKM has two new keyword abilities, two new keyword actions and one symbol redesign.

![Icon_Keyword_Disguise](https://github.com/andrewgioia/mana/assets/128204978/5783b96a-6eca-4806-86a1-42182e5ffe1f) - [Disguise](https://mtg.fandom.com/wiki/Disguise) is an updated version of [Morph](https://mtg.fandom.com/wiki/Morph) where the face-down creature now has ward {2}. Otherwise it's exactly the same.

![Icon_Keyword_Cloak](https://github.com/andrewgioia/mana/assets/128204978/8c8bc003-7406-4ecc-bd5d-c1e56debe3ee) - [Cloak](https://mtg.fandom.com/wiki/Cloak) this is the new version of [Manifest](https://mtg.fandom.com/wiki/Manifest) where the manifested card has ward {2}.

![Icon_Keyword_CollectEvidence](https://github.com/andrewgioia/mana/assets/128204978/013a1b96-e3ba-4813-a61f-c95cc438ae40) ![Icon_Keyword_CollectEvidence_Active](https://github.com/andrewgioia/mana/assets/128204978/1a568764-cbdb-4f22-bf29-6df6a16f5abd) - [Collect evidence](https://mtg.fandom.com/wiki/Collect_evidence) is a keyword ability that is used as a cost. It allows players to exile cards with total mana value N or greater from their graveyard, where N is the collect evidence number, to trigger an ability, buff their spells or permanents, etc. It's kind of like Kicker meets Delve but for mana values.

![Icon_Keyword_Suspect](https://github.com/andrewgioia/mana/assets/128204978/2943c917-6df1-4445-9dc7-b3218cde1b82) - [Suspect](https://mtg.fandom.com/wiki/Suspect) is a keyword action and creature designation. Suspected creatures gain menace and "this creature can't block". They are also "suspected" for cards that care about that.

![Icon_Keyword_Surveil](https://github.com/andrewgioia/mana/assets/128204978/0542f824-e292-4ee4-9197-f29b3b814410) - The [Surveil](https://mtg.fandom.com/wiki/Surveil) symbol has been redesigned for Murders at Karlov Manor. Similar to the change with Convoke in March of the Machine, WotC have moved away from the guild symbol to a more generic symbol.

**Arena Designation:**
![Icon_Keyword_SolvedCase_Active](https://github.com/andrewgioia/mana/assets/128204978/1ef0fef8-c4fe-4855-9474-66243d04a640) - [Case](https://mtg.fandom.com/wiki/Case) cards get a marker when they're solved to indicate their status. Arena uses a very different symbol from the one used in tabletop punch-cards (most likely due to the limited space at the small scale Arena uses)..
![Solved_Case](https://github.com/andrewgioia/mana/assets/128204978/8b42ac55-1df3-439d-a5cc-5aae3fabd80b)

**Misc:**
The set also reuses [Investigate](https://mtg.fandom.com/wiki/Investigate) and [Stun counters](https://mtg.fandom.com/wiki/Stun_counter), but there doesn't appear to be any changes in those icons from their last uses.

**Comment by andrewgioia** [comment]
Wow I just realized the extent of the extras you shared here, this is wild. The good news is they seem very easy to trace/draw but that is a ton of extra glyphs to get in.

**Comment by andrewgioia** [comment]
Added in v1.17.0!
