### ISSUE TITLE
ms-2 conflicts with Bootstrap

### ISSUE THREAD

**Issue by SerratedSharp** [andrewgioia/mana#123]
If used on a site with bootstrap, `ms-2` gets picked up by bootstrap a `m`argin `s`tart padding of 2, and adds additional spacing in front of the symbol.

**Comment by andrewgioia** [comment]
Really good catch here, that's a pretty common utility class. 

I'm not really sure what to do to properly fix this other than change the entire prefix. Short of that I can just override the start padding whenever the `.ms` class is also present, so:

```
.ms.ms-2 {
  margin-left: initial;
} 
```

**Comment by andrewgioia** [comment]
Added in v1.17.0!
