### ISSUE TITLE
[Request] Tap icon (4ED to SCG)

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#124]
![image](https://github.com/andrewgioia/mana/assets/4212200/c3ce6bcc-178f-472a-94d8-dbb8b5f6b7f2)

I was analyzing the symbols that were deprecated over the years and noticed that Mana does not have the tap symbol used from 4ED to SCG.

I'm requesting it's addition :)

**Comment by andrewgioia** [comment]
Added in v1.17.0!
