### ISSUE TITLE
[Set Release] Outlaws of Thunder Junction roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#125]
Hi @andrewgioia, just putting a roundup of the new symbols courtesy of the Outlaws of Thunder Junction (OTJ) release.

**Arena Ability Symbols:**
OTJ has three new keyword abilities, and one sort-of-designation.

![MTGA_Plot](https://github.com/andrewgioia/mana/assets/128204978/309014a7-6266-4db1-ac64-69169594615d) - [Plot](https://mtg.fandom.com/wiki/Plot) is similar to Foretell in that you pre-pay mana to exile the spell then cast it later. Plotted cards are free but can only be cast as a sorcery.

![MTGA_Saddle](https://github.com/andrewgioia/mana/assets/128204978/ec17ceea-fe77-43b6-917c-f3f4dae35c33) - [Saddle](https://mtg.fandom.com/wiki/Saddle) is the creature version of Crew.

![MTGA_Spree](https://github.com/andrewgioia/mana/assets/128204978/81146e8f-8287-43e9-8714-8fcf39c49c43) - [Spree](https://mtg.fandom.com/wiki/Spree) is a special version of modal spells where each mode has its own separate cost and you can mix and match the modes however you like.

![MTGA_Crimes](https://github.com/andrewgioia/mana/assets/128204978/88ce4d69-866d-4c93-9ae5-2131ef22ffd1) - [Crime](https://mtg.fandom.com/wiki/Committing_a_crime) is a new term and means any time a player "casts a spell, activates an ability, or puts a triggered ability on the stack and that spell or ability targets at least one opponent; at least one permanent, spell, or ability an opponent controls; and/or at least one card in an opponent’s graveyard." This symbol is **not** used for spells that _are_ crimes, it's used for cards that get/grant a bonus when a player commits a crime.

**Card Symbols**
OTJ has introduced a new card frame icon for spells with Spree. It's meant to be a way for players to quickly tell when a card has additional costs and those costs are mandatory. The icon itself has no meaning in the rules though, making it similar to the Odyssey block [Tombstone icon](https://mtg.fandom.com/wiki/Tombstone_icon) (labelled as [flashback] in Mana). The [Plus icon](https://mtg.fandom.com/wiki/Plus_icon) modifies the right-hand side of a card's title bar and sits after the card's mana cost.

A Spree spell with the Plus icon in the top right corner.
![FInal_Showdown](https://github.com/andrewgioia/mana/assets/128204978/a19379d5-0ca1-447f-942f-4ec4538fe3b0)

My attempt at a trace.
![Plus-opt](https://github.com/andrewgioia/mana/assets/128204978/21edaaa4-b1ca-4a3e-9016-8203cc8ac3d9)

**Comment by andrewgioia** [comment]
Added in v1.17.0!
