### ISSUE TITLE
Update Lifelink icon

### ISSUE THREAD

**Issue by cytryn** [andrewgioia/mana#126]
Hey, I noticed that the Lifelink icon is different from what we see on MTGA

This is what it looks like:

![image](https://github.com/andrewgioia/mana/assets/735750/448b5045-286c-4b7c-a48c-f9e7c1fa2f3f)

**Comment by andrewgioia** [comment]
Looks like the punch card that RivalRowan shared in #133 has a high res version of this which is even better

**Comment by RivalRowan** [comment]
I've also got an isolated version, if that helps.
![MTGA_Lifelink](https://github.com/user-attachments/assets/96a2d92c-6b03-432d-8369-f2de40ba9857)

**Comment by andrewgioia** [comment]
Added in v1.17.0!
