### ISSUE TITLE
[New] Pawprint

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#129]
A new symbol exclusive to modal Bloomburrow cards.

![image](https://github.com/andrewgioia/mana/assets/4212200/e916e74c-55eb-4436-9f17-347d4ad2eb27)

Scryfall trace
[https://svgs.scryfall.io/card-symbols/J.svg](https://svgs.scryfall.io/card-symbols/J.svg)

**Comment by RivalRowan** [comment]
**Adding some context:**
The new symbol is called "pawprint" and it is used as a points system on a single cycle of modal cards in _Bloomburrow_. The pawprints allow a player to choose multiple modes but only in certain combinations and with an upper limit, unlike Multikicker. 

Pawprints are like a resource, but are explicitly not a resource. Players can't generate or earn pawprints. You don't get pawprint counters. Unused pawprints don't float in a pool or carry over step and phases. They only exist as the spell is cast when choosing modes. Each individual card defines the maximum number of pawprints you can utilize and whether using them all is optional or mandatory.

The plaintext equivalent to the pawprint symbol is `{P}`. Prior to _Bloomburrow_, this was the plaintext for Phyrexian mana (as noted in the Mana documentation). The plaintext for Phyrexian mana is being changed to `{H}` as of _Bloomburrow_.

Mechanics article: https://magic.wizards.com/en/news/feature/bloomburrow-mechanics
Source for plaintext change: https://twitter.com/Dunkatog/status/1811520152011440177

![blb-68-season-of-weaving](https://github.com/user-attachments/assets/d85dd89e-5d12-48c7-831b-87c3418a7bee)

**Comment by andrewgioia** [comment]
Thanks so much guys, I think the remaining issue for me is how to handle backwards compatibility with {P} and {H} now. {P} was used as the Phyrexian Mana symbol and I guess this is just going to be a breaking change.

Happy to entertain any suggestions though.

**Comment by 4eveRS** [comment]
I had the same issue, how to tackle the new pawprint symbol. Currently Scryfall utilizes the official definition of {P} and it doesn't conflict "yet", because phyrexian mana utilizes a pattern of {color/phyrexian symbol}, for example: {R/P} for red phyrexian mana.

So it currently does not require any changes, but if you want to future proof it, you could add a new CSS selectors to phyrexian mana along with the current one.

**Comment by RivalRowan** [comment]
> Currently Scryfall utilizes the official definition of {P} and it doesn't conflict "yet", because phyrexian mana utilizes a pattern of {color/P}, for example: {R/P} for red phyrexian mana.

This is not quite accurate. The colored Phyrexian mana symbol plaintext, both on Scryfall and the official WotC plaintext, remains in the form of {_color_/P}. This remains true even after the change of {P} to {H}.

What has changed is the "generic Phyrexian mana" symbol has changed from {P} to {H}. There is only one card that uses this symbol, [Rage Extractor](https://scryfall.com/card/nph/91/rage-extractor) (NPH). The problem Andrew's articulating is that while WotC only uses they symbol in one place, most users of Mana are probably using it as the de facto Phyrexian symbol.

Unfortunately I think a breaking change is the only answer. Unless straying away from WotC official plaintext is ok. Then {P} could remain as the Phyrexian mana symbol and the pawprint could be labelled {Paw}.

**Comment by andrewgioia** [comment]
> The problem Andrew's articulating is that while WotC only uses they symbol in one place, most users of Mana are probably using it as the de facto Phyrexian symbol.

Yeah this is precisely it. It's unfortunate because I imagine the Phyrexian symbol is and will be way more used than the Pawprint symbol. 

For now I think we'll keep Phyrexian as `.ms-p` and add`.ms-h` for it, and Pawprint will be `.ms-paw` with the ability to override this via Sass variable. I'll also announce that this will be changed in a future release to conform to WotC's name change though and just give everyone a bit of time to be aware.

**Comment by RivalRowan** [comment]
Seems like a pretty reasonable solution.

**Comment by andrewgioia** [comment]
Thanks all, this was added in v1.17.0 as so:

* `.ms-p` is still the Phyrexian mana symbol
* `.ms-h` is now also the Phyrexian mana symbol
* `.ms-paw` is the Pawprint
* There's a Sass variable `$ms-phyrexian-h` that will make `.ms-p` the pawprint and only use the `h` as Phyrexian by itself.
* All of the split costs still use `p` in them.
