### ISSUE TITLE
Enhancement: icons for schemes, vanguard, planes, conspiracies, etc

### ISSUE THREAD

**Issue by arjenbrandenburgh** [andrewgioia/mana#13]
Currently there are unique icons for Creatures, Instants, Sorceries, etc. Maybe, to be entirely complete, icons could be added for:
- Schemes (example: [All in Good Time](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=212648))
- Vanguard cards (example: [Tawnos](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=12328))
- Planes (example: [Interplanar Tunnel](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=226549))
- Conspiracies (example: [Secret Summoning](http://gatherer.wizards.com/Pages/Card/Details.aspx?name=Secret+Summoning))
- Tokens
- Phenomenon (example: [Spatial Merging](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=226546))

**Comment by andrewgioia** [comment]
@cybey thanks for the suggestion here. Are you aware of any existing symbols that these card types use, or are you requesting that we create them?

I took a look and can't seem to find anything for these, other than perhaps the +/- abilities on the Vanguard cards. The schemes are in Archenemy and that icon is in Keyrune (for set symbols). Likewise the Planes and Phenomenons are in the Planechase sets (also in Keyrune) and the Conspiracy sets have their own set symbols there as well.

If you know of any missing symbols definitely drop them here and I can take a look.

**Comment by cybey** [comment]
I was also searching for icons that may fit the above types, but I agree that it's hard to actually find something fitting.

You could argue that you can use the Conspiracy icon for the Conspiracies, however, there are multiple sets where Conspiracies are printed in. Just figured I'd put this enhancement idea here, but can imagine if it's just not very possible.

**Comment by andrewgioia** [comment]
Just an update as I hope to tie this issue out soon; given the Future Sight card type symbols I do think there should be corresponding symbols for the other types that exist, from [Rule 3](http://media.wizards.com/2018/downloads/MagicCompRules%2020180713.txt):

- [ ] 301. Artifacts
- [ ] 302. Creatures
- [ ] 303. Enchantments
- [ ] 304. Instants
- [ ] 305. Lands
- [ ] 306. Planeswalkers
- [ ] 307. Sorceries
- [ ] 308. Tribals
- [ ] 309. Planes
- [ ] 310. Phenomena
- [ ] 311. Vanguards
- [ ] 312. Schemes
- [ ] 313. Conspiracies

My inclination is to use the symbol for the set that these ones first appeared: Planes ([Planechase](https://andrewgioia.github.io/Keyrune/icons.html?icon=hop)), Phenomena ([Planechase 2012](https://andrewgioia.github.io/Keyrune/icons.html?icon=hop)), Vanguards ([Vanguard](https://andrewgioia.github.io/Keyrune/icons.html?icon=van)), Schemes ([Archenemy](https://andrewgioia.github.io/Keyrune/icons.html?icon=arc)), and Conspiracies ([Conspiracy](https://andrewgioia.github.io/Keyrune/icons.html?icon=cns)).

Tribal is the only one that would need a custom symbol. I'll try to go digging to see if WOTC ever used anything.

**Comment by fenhl** [comment]
For tokens, I believe a rectangle with a rounded top (the shape of the art box on token cards before M20, and still used to distinguish tokens from cards on MTG Arena today) would work.

**Comment by andrewgioia** [comment]
_Finally_ added in 1.9!
