### ISSUE TITLE
[Set Release] Bloomburrow roundup

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/mana#130]
Hi @andrewgioia, just putting a roundup of the new symbols courtesy of the Bloomburrow (BLB) release.

**Arena Ability Symbols:**
BLB has two new keyword abilities, one new ability word, one new keyword action, one new rules term, and one new resource (sort of).

![MTGA_ Gift](https://github.com/user-attachments/assets/8b53efdd-5b64-402b-b8e2-a03fc5401e30) - [Gift](https://mtg.fandom.com/wiki/Gift) is a keyword ability that lets you promise an opponent a gift as an additional cost to casting a spell. If you do, the spell gains some additional effect but your opponent gets their gift first. What the gift is gets defined by each spell and can range from your opponent drawing a card, to creating a token creature, to giving an opponent an extra turn.

![MTGA_ Offspring](https://github.com/user-attachments/assets/c7e745d5-0875-441b-a499-ef305f58b936) - [Offspring](https://mtg.fandom.com/wiki/Offspring) is a keyword ability that functions an additional cost and is restricted to creatures. You pay it as you cast the spell and it lets you create a copy of the original spell except it's a 1/1. It's similar to Squad and related to Embalm or Eternalize.

![MTGA_ Valiant](https://github.com/user-attachments/assets/4ec0b96d-d594-4678-b34d-5b5ca2441374) - [Valiant](https://mtg.fandom.com/wiki/Valiant) is an ability word and a variation on [Heroic](https://mtg.fandom.com/wiki/Heroic) from Theros block. Valiant only triggers once per turn but unlike Heoric it triggers off both spells and abilities.

![MTGA_Forage](https://github.com/user-attachments/assets/afd662c7-35ff-478c-a74d-ebf360a43a80) - [Forage](https://mtg.fandom.com/wiki/Forage) is a keyword action that gets used as an additional cost. To forage, you can either sacrifice a Food (token or non-token, doesn't matter) or exile three cards from your graveyard.

![MTGA_ Expend](https://github.com/user-attachments/assets/24351bff-6ec2-4585-ae6e-911cfc4f4b36) - [Expend](https://mtg.fandom.com/wiki/Expend) N is a new rules term that refers to spending your Nth mana to cast a spell this turn. If you have a creature with expend 4 on the battlefield and you spend four mana to cast a spell, that fourth mana triggers the creature's expend effect. Expend is kept track of across the whole turn, so if you spend four mana to play a creature with expend 4, it won't trigger off it's own casting. It's also fixed to the Nth value so if you cast two four drops in a turn, you've expended all integers between 1 and 8 but only once each. There's no double dipping. Expend doesn't count mana spent on abilities or non-spell functions (e.g. the tax to roll the planar die in a Planechase game).

**Card Symbols**
BLB has introduced a new resource icon in the form of "pawprints". This symbol is outlined in  **#129 [New] Pawprint**.

**Comment by andrewgioia** [comment]
Added in v1.17.0!
