### ISSUE TITLE
[New] Saga Symbol VI

### ISSUE THREAD

**Issue by suitangi** [andrewgioia/mana#131]
Sagas can go up to `VI` lore counters now thanks to [Long List of the Ents](https://scryfall.com/card/ltr/174/long-list-of-the-ents) from the LoTR set:

![image](https://github.com/user-attachments/assets/4b1058d5-d109-44c2-9135-5ac171ca13c6)

**Comment by andrewgioia** [comment]
This was actually already in there! Closing as done.
