### ISSUE TITLE
[Counter] Rad Counter - MTGO

### ISSUE THREAD

**Issue by ElectroShade** [andrewgioia/mana#132]
The Fallout set was released on Magic Online earlier this month and introduced the following icon for rad counters. It’s the same symbol featured on the helper card as well, a rotated variant of the normal radiation symbol.

- https://mtg.fandom.com/wiki/Rad_counter
- https://mtg.fandom.com/wiki/File:Rad.svg

**Comment by RivalRowan** [comment]
Yeah, I did the trace for the MTG Wiki. Here's a copy + the original source material I worked with.
![Rad counters](https://github.com/user-attachments/assets/7a2ee678-72ce-45ac-831e-813315bbe2c5)
![Rad](https://github.com/user-attachments/assets/5eced125-5a5c-4a98-a3ec-23a897949704)
(Modified from https://commons.wikimedia.org/wiki/File:Radiation_sign_round.svg)

**Comment by andrewgioia** [comment]
Added in v1.17.0!
