### ISSUE TITLE
[Set Release] Duskmourn 

### ISSUE THREAD

**Issue by ElectroShade** [andrewgioia/mana#133]
Arena symbols:

- Survival: https://mtg.fandom.com/wiki/File:MTGA_Survival.png
- Impending: https://mtg.fandom.com/wiki/File:MTGA_Impending.png
- Manifest Dread: https://mtg.fandom.com/wiki/File:MTGA_Manifest_Dread.png
- Eerie: https://mtg.fandom.com/wiki/File:MTGA_Eerie.png
- Locked symbol on new room cards: https://mtg.fandom.com/wiki/File:Locked_Room_MTGO.png

**Comment by RivalRowan** [comment]
Hi @andrewgioia, sorry I'm running late with this one and accidentally opend a duplicate ticket (#138).
Here's the roundup of the new symbols courtesy of the _Duskmourn: House of Horror_ (DSK) release.

**Arena Ability Symbols:**
DSK has one new keyword ability, two new ability words, one new keyword action, and one new Enchantment subtype that comes with a bunch of rules.

![Icon_Keyword_Impending](https://github.com/user-attachments/assets/6435988e-6189-4b70-8e6f-2e3fa96e1b17) ![Icon_Keyword_Impending_Active](https://github.com/user-attachments/assets/516168bb-4dd9-4e93-af7e-2093c913dc68) - [Impending](https://mtg.fandom.com/wiki/Impending) is a keyword ability that is essentially [suspend](https://mtg.fandom.com/wiki/Suspend) for permanents. You achieve this by having the permanent enter the battlefield as a non-creature.

![Icon_Keyword_ Eerie](https://github.com/user-attachments/assets/32798fc3-5cbc-4710-8d5e-92760752bf04) - [Eerie](https://mtg.fandom.com/wiki/Eerie) is an ability word that functions the same as [Constellation](https://mtg.fandom.com/wiki/Constellation) but also triggers off the set's new Enchantment type, Room, becoming fully unlocked.

![Icon_Keyword_Survival](https://github.com/user-attachments/assets/59f948d5-2f35-4c12-a655-41bad16c4a80) - [Survival](https://mtg.fandom.com/wiki/Survival) is an ability word that indicates a triggered ability that triggers at the beginning of the controller's [second main phase](https://mtg.fandom.com/wiki/Main_phase) if the creature with the ability is tapped.

![Icon_Keyword_ ManifestDread](https://github.com/user-attachments/assets/66f6af2a-a6a1-438f-8578-35685706ce41) - [Manifest Dread](https://mtg.fandom.com/wiki/Manifest#Manifest_Dread) is a twist on Manifest that essentially allows you to surveil 2 before you manifest the top card of your library.

**Unlocking a door**
Duskmourn introduced split card permanents to _Magic_ in the form of [Room](https://mtg.fandom.com/wiki/Room) enchantments. The side you cast enters "unlocked" and the other side enters "locked". You can cast either half the same way you would a split card but while it's on the battlefield you can pay the mana cost of the locked half to unlock it and that will grant you that side's abilities as well. To help players keep track of which side is locked and which isn't, WotC have tried a few different options.

Tabletop punch out cards:
<img src="https://github.com/user-attachments/assets/a1c66f14-96b0-40dc-84a2-42b5f7e52969" width=300> <img src="https://github.com/user-attachments/assets/f9f954d5-191a-4d9b-af94-408b96053f95" width=300>

MTGO card overlay:
![Locked_Room_MTGO](https://github.com/user-attachments/assets/5596f2dc-e966-4158-83bc-d316e4af7c5d)

MTG Arena overlay:
(Coming soon! It's a glowy keyhole over the card but it's hard to get a good image of the thing)

**Comment by andrewgioia** [comment]
Moving Lock out to the next point release

**Comment by andrewgioia** [comment]
Added in v1.17.0!
