### ISSUE TITLE
[Set Release] Mystery Booster 2

### ISSUE THREAD

**Issue by ElectroShade** [andrewgioia/mana#134]
Mystery Booster 2 introduced a few new simple letter symbols.

The Boulder Jockey card introduced a new D symbol for Land drops: https://scryfall.com/card/mb2/324/boulder-jockey & https://mtg.fandom.com/wiki/Land_drop

Other cards introduced a new L symbol for legendary sourced mana: https://scryfall.com/card/mb2/339/keeper-of-the-crown-coronation-of-the-wilds & https://mtg.fandom.com/wiki/Legendary?so=search#Legendary_costs

**Comment by andrewgioia** [comment]
Added in v1.17.0!
