### ISSUE TITLE
[Request] Party Class Symbols

### ISSUE THREAD

**Issue by ElectroShade** [andrewgioia/mana#136]
A bit obscure but it looks like back with the release Zendikar Rising, Wizards released some promotional symbols for each of the classes in the Party mechanic:

Cleric: https://mtg.fandom.com/wiki/File:ZNR_Cleric_symbol.jpg
Rogue: https://mtg.fandom.com/wiki/File:ZNR_Rogue_symbol.jpg
Warrior: https://mtg.fandom.com/wiki/File:ZNR_Warrior_symbol.jpg
Wizard: https://mtg.fandom.com/wiki/File:ZNR_Wizard_symbol.jpg

**Comment by andrewgioia** [comment]
Wow cool, I had no idea about these. Will definitely get them in.

**Comment by andrewgioia** [comment]
Added in v1.17.0!
