### ISSUE TITLE
[Request] Eldraine Court Symbols

### ISSUE THREAD

**Issue by ElectroShade** [andrewgioia/mana#137]
The five courts of Eldraine each have their own symbols which could potentially be included assuming they aren't too complicated to be traced and added. Just a thought after seeing all the other faction ones:

https://magic.wizards.com/en/news/feature/planeswalkers-guide-eldraine-2019-10-31

Ardenvale: https://mtg.fandom.com/wiki/File:Ardenvale_symbol.png
Vantress: https://mtg.fandom.com/wiki/File:Vantress_symbol.png
Locthwain: https://mtg.fandom.com/wiki/File:Locthhwain_symbol.png
Embereth: https://mtg.fandom.com/wiki/File:Embereth_symbol.png
Garenbrig: https://mtg.fandom.com/wiki/File:Garenbrig_symbol.png

**Comment by andrewgioia** [comment]
These are really cool as well, I think the 2 issues are that they're very complicated/multicolor and I'm not sure they've ever been printed as a card watermark. Do you know if these were used anywhere outside of marketing materials? I'd love to know where you all found these originally too.

**Comment by andrewgioia** [comment]
Ah! I should've read that more closely 🤦 

I think if they weren't on the cards we can leave them out for now, but this is a great reference if/when WotC does ever include them as watermarks.
