### ISSUE TITLE
Hybrid Colorless/color symbols

### ISSUE THREAD

**Issue by ivaggione** [andrewgioia/mana#139]
Hi @andrewgioia, thanks a lot for all the work maintaining these icons libraries, it's a great resource.
Are there any plans to include the hybrid colorless/color symbols found in Ulalek?
![m3c-4-ulalek-fused-atrocity](https://github.com/user-attachments/assets/81a60831-feb1-4748-80ad-ca471b54ec14)

Thanks again!

**Comment by andrewgioia** [comment]
Yes great catch, sorry I must have missed this one entirely. I'll get this one in 1.17.1!

**Comment by andrewgioia** [comment]
Added in 1.17.1
