### ISSUE TITLE
Energy icon?

### ISSUE THREAD

**Issue by scole-scea** [andrewgioia/Mana#14]
Do you create the fonts yourself? If so, can I plead for an energy icon?

**Comment by andrewgioia** [comment]
Yes I do @scole-scea, I've been meaning to add this one when a higher resolution version of the energy symbol got released. I have a fairly good one now that I should add in, and can update if a better one exists.

**Comment by scole-scea** [comment]
Awesome. Thanks! I've been meaning to figure out how to make fonts myself, but never got up the nerve to climb the learning curve...

**Comment by rosscooperman** [comment]
@andrewgioia do you have a source for vector version or do you just trace them?  I'm happy to pitch in if you wanna shoot me whatever you have as a source and a pointer in the right direction.  I've been known to dabble in vectors now and then 😉.

**Comment by andrewgioia** [comment]
@scole-scea @rosscooperman I just pushed up the energy icon if you guys want to take a look. The docs are updated too.

@rosscooperman unfortunately I don't have a source for any vectors, I trace high resolution PNGs when I can find them. Usually on the mothership there are decently high res versions of these things, for the energy one I had to take a screenshot of the announcement when they live streamed it so the quality isn't what I would have liked it to be.

If you're looking to contribute that would be fantastic! There's an open issue right now on other card types that I'm about to comment on, if you're aware of any mana/resource symbols that are missing please feel free to submit a new issue to track it and then a PR if you have it ready for review.

**Comment by andrewgioia** [comment]
@rosscooperman I forgot to mention as well, I manage these projects in [Icomoon](http://icomoon.io) and upload single layer SVGs that are typically 512px high and variable width. If you're interested in the process more feel free to email me and I can go over anything.

**Comment by rosscooperman** [comment]
@andrewgioia makes sense.  Energy looks great!  I'll take a look at that issue over the weekend and see if I can help out.
