### ISSUE TITLE
Enhancement: Guild/Wedge Watermark Symbols (Ravinica, Tarkir)

### ISSUE THREAD

**Issue by Saeris** [andrewgioia/Mana#16]
Would it be possible to add watermark symbols to this set? I'm not sure whether this request would be better suited for Mana or Keyrune.

Basically what I'm looking for is the addition of the Guild/Wedge symbols from the Ravnica and Tarkir blocks (sadly Alara didn't have Shard symbols, but hopefully they'll come back and add them!).

I rounded up links to the various PNG files I could find for each. Vectors might exist somewhere, but they didn't come up on the first try.

**Ravnica Guilds (Newest symbols):**
- Simic Combine: http://orig01.deviantart.net/1b63/f/2013/181/5/5/simic_combine_guild_symbol_by_drdraze-d6b7zmv.png
- Selesnya Conclave: http://orig14.deviantart.net/a7dc/f/2013/180/5/d/selesnya_conclave_guild_symbol_by_drdraze-d6b7zgz.png
- Cult of Rakdos: http://orig09.deviantart.net/f31b/f/2013/180/4/b/cult_of_rakdos_guild_symbol_by_drdraze-d6b7yxu.png
- Orzhov Syndicate: http://orig11.deviantart.net/d186/f/2013/180/2/c/orzhov_syndicate_guild_symbol_by_drdraze-d6b7yr6.png
- Izzet League: http://orig13.deviantart.net/1bf5/f/2014/204/f/6/izzet_league_guild_symbol_by_drdraze-d6b7yd9.png
- Gruul Clans: http://orig13.deviantart.net/b8e3/f/2013/250/f/0/gruul_clans_guild_symbol_by_drdraze-d6b7xzm.png
- Golgari Swarm: http://orig10.deviantart.net/f95d/f/2013/181/2/0/golgari_swarm_guild_symbol_by_drdraze-d6b7x1l.png
- House Dimir: http://orig10.deviantart.net/1d36/f/2013/180/d/2/house_dimir_guild_symbol_by_drdraze-d6b7wgo.png
- Boros Legion: http://orig12.deviantart.net/8ebe/f/2013/181/2/f/boros_legion_guild_symbol_by_drdraze-d6b7vzw.png
- Azorius Senate: http://orig12.deviantart.net/e9e9/f/2013/181/8/1/azorius_senate_guild_symbol_by_drdraze-d6b7umm.png

**Tarkir Clans:**
- Abzan: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/2/2e/Clan_Symbol_Abzan.png?version=f976da2382e24f677623f12f9830218a
- Jeskai: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/f/f3/Clan_Symbol_Jeskai.png?version=9e4cfb3ff076d8f25302f6e11b965b62
- Sultai: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/2/22/Clan_Symbol_Sultai.png?version=6b64e78d0a1e5a5fd5e6b04e5d170229
- Mardu: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/4/4e/Clan_Symbol_Mardu.png?version=5cd6b698dcbbb01f12d552a727c190cd
- Temur: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/2/2f/Clan_Symbol_Temur.png?version=e36b90ed027bbf3b5f688d8e61b17a15

**Tarkir Dragon Watermarks:**
- Atarka: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/7/73/Clan_Symbol_Atarka.png?version=c137d684627079e4bbe314351d562ff2
- Dromoka: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/a/a5/Clan_Symbol_Dromoka.png?version=6d59761dbeda1209ea62a7b1dca8fd29
- Kolaghan: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/5/5b/Clan_Symbol_Kolaghan.png?version=3284c7fd16195661be58dcdf5e5cedfb
- Ojutai: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/0/0f/Clan_Symbol_Ojutai.png?version=546987b5546233c9877f4d8ff8b5a74e
- Silumgar: https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/6/6a/Clan_Symbol_Silumgar.png?version=54d3706aea6698218b5891797ca0f315

Thanks for putting this all together! It's been of tremendous help in my project!

**Comment by andrewgioia** [comment]
@Saeris Thank you for these excellent source images! I'm going to knock these out this afternoon.

**Comment by Saeris** [comment]
No problem! Glad to see these will be added. Thanks!

**Comment by andrewgioia** [comment]
@Saeris wow sorry about the delay here, I finally found some time today to create all of these and update everything. If you pull down or update via Bower/NPM it should have everything, you can see them live on the [docs page](https://andrewgioia.github.io/Mana/icons.html)

**Comment by Saeris** [comment]
Those are excellent! Thank you very much for your work!

**Comment by andrewgioia** [comment]
Sure thing! Thanks for using them :)
