### ISSUE TITLE
Documentation: Add NPM Install Instructions

### ISSUE THREAD

**Issue by Saeris** [andrewgioia/Mana#17]
I kinda feel dumb for not thinking to check the NPM registry first (I originally found this project through a random website), but at first I thought in order to add this to my project I needed to download it directly from github in NPM.

To reduce confusion for other newcomers, I suggest adding a short blurb on installing via NPM in the project readme. This of course also applies to Keyrune.

**Comment by andrewgioia** [comment]
Great idea @Saeris, I can update that quickly. I'll bundle it with your other Ravnica/Khans suggestion as well.

**Comment by andrewgioia** [comment]
@Saeris just updated the [readme](https://github.com/andrewgioia/Mana#installing) to include a section on installing via Bower/NPM.

For anyone else interested (and reading this for some reason :P) I added a section on desktop use below that.
