### ISSUE TITLE
Wrong classes in documentation examples

### ISSUE THREAD

**Issue by Arlanthir** [andrewgioia/Mana#20]
Hi,

This issue is not in the code itself but in the documentation.

The size and fixed width classes in the https://andrewgioia.github.io/Mana/attributes.html examples are written as ss-* instead of ms-*.

In the case of the size examples, the ms-* text is there but only outside the HTML code of each example.

The classes in the descriptions above the examples are correct.

Thanks for your excellent fonts!

**Comment by andrewgioia** [comment]
Thanks @Arlanthir this should be fixed now
