### ISSUE TITLE
Portal power and toughness icons

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/Mana#25]
Submitted [via Twitter](https://twitter.com/releasethedogs/status/892588195128287234) by @releasethedogs 

Portal has a sword and shield as power and toughness icons in the P/T area. Highest res version I could find online: 

![schermata 2017-10-16 alle 1 05 57 pm](https://user-images.githubusercontent.com/221473/31625148-028cd6f4-b273-11e7-8cd4-90d670a727a6.png)

From: http://www.abugames.com/images/products/actualpictureitems/30499.jpg

**Comment by yandere-sliver** [comment]
we have both symbols in the wiki

https://mtg.gamepedia.com/File:Power.svg
https://mtg.gamepedia.com/File:Toughness.svg

**Comment by andrewgioia** [comment]
Thanks @yandere-sliver I'm going to use these and update this tonight or tomorrow morning.

**Comment by releasethedogs** [comment]
Thank you!

**Comment by andrewgioia** [comment]
@releasethedogs Added in the latest 1.4.0!
