### ISSUE TITLE
New symbol for new double-face Enchantment/Land

### ISSUE THREAD

**Issue by Nightbr** [andrewgioia/Mana#26]
Hey,

it could be nice if we can add these symbols:
![enchant](https://user-images.githubusercontent.com/4228646/31730457-42d3f394-b432-11e7-85f1-45dcfa874c99.png) 
![land](https://user-images.githubusercontent.com/4228646/31730460-46238550-b432-11e7-86ef-5b454bf4cbd9.png)

From the new double-face card.

https://scryfall.com/card/xln/22

Thank you for your work!

**Comment by andrewgioia** [comment]
@Nightbr added as of 1.4.0!
