### ISSUE TITLE
Phyrexian mana symbols have issues with css columns

### ISSUE THREAD

**Issue by KingSupernova31** [andrewgioia/Mana#31]
If used on a webpage divided into columns, the phyrexian mana symbols will sometimes stop rendering properly. To replicate this, download the zip file and add
```html
<style>
	body {
		column-count: 2;
	}
</style>
```
to the head. If the page is wide enough they will render correctly, but as you shrink the width of the page, the black symbol will disappear from the phyrexian mana symbols only. (The colored background circle will remain.) You can also increase the number of columns in lieu of shrinking the page.

**Comment by KingSupernova31** [comment]
Update: This did not happen to me on Firefox 60.0.1 or Safari 9.1.3, only on Chrome 66.0.3359.181.

**Comment by andrewgioia** [comment]
@KingSupernova31 thanks for reporting this, I can't seem to replicate in the latest Chrome (67.0.3396.99). Firefox and Safari also still render it correctly. Do you still see the problem in Chrome?

**Comment by KingSupernova31** [comment]
I am also unable to replicate in the latest Chrome. Looks like it only affected some version then.

**Comment by andrewgioia** [comment]
Ok cool, glad it got resolved there. Thanks again for reporting!
