### ISSUE TITLE
Mana and Keyrunes

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Mana#33]
Hey, just a simple question. Did you ever think about combining these two fonts. Or are they too different?

**Comment by oniice** [comment]
@yandere-sliver what would the benefit be of combining the two? Besides one yarn install?
To me it makes most sense having two light weight packages doing specific jobs than combing them both, but thats just me...

**Comment by yandere-sliver** [comment]
Essentially because I don't follow the separation. 

If this font would handle only symbols with "movable" parts: Mana, Loyality, Level Up, Saga Status. 
That would make sense to keep these separate.

However this font features a lot of symbols which are essentially a black  symbol  against white background (or whatever color or gradient you chose). So have of the mana font is very close to the keyrune font anyway: clan, guild, and type symbols, etc. Especially the watermarks since many of the watermarks are keyrunes thanks to M25. 

And if you are mixing anyway... Why not combine the two to make one complete Magic Font project?

**Comment by andrewgioia** [comment]
I appreciate the feedback @yandere-sliver. The original intent was for Keyrune to host a complete set of all MTG set symbols specifically to identify expansions and other distinct sets. Mana is for the mana symbols obviously and has grown to include other symbols in the card text box. 

I feel as if this distinction is significant enough to justify keeping the two projects separate as a lot of use cases have no need for mana and other symbols. I also agree with @oniice in that it isn't significant enough overhead to include two yarn/npm projects if you need them both.
