### ISSUE TITLE
Additional Watermarks

### ISSUE THREAD

**Issue by Thom1729** [andrewgioia/mana#34]
### Unique card watermarks 

There are a number of card watermarks that are unique to various sets or themes. Currently I plan to add all of these that are not just the set symbol. The following is a "complete" current list, pulled from MTGJSON's `watermarks` property, and based originally on @Thom1729's excellent initial issue from many years ago (full content below).

- [x] abzan - available already
- [x] agentsofsneak
- [x] arena
- [x] atarka - available already
- [x] azorius - available already
- [x] boros - available already
- [x] brokers
- [x] cabaretti
- [x] colorpie
- [x] conspiracy - stamp is very textured, will be tough to create
- [x] corocoro
- [x] crossbreedlabs
- [x] d&d
- [x] dci
- [x] dengekimaoh
- [x] desparked
- [x] dimir - available already
- [x] dromoka - available already
- [x] flavor (Aesthetic Consultation) - artist pen available in mana already
- [x] flavor (Farewell to Arms)
- [x] #115
- [x] flavor (Monkey Monkey Monkey) - drawn
- [x] flavor (Mox Lotus)
- [x] flavor (My First Tome) - drawn
- [x] flavor (Shoe Tree)
- [x] flavor (When Fluffy Bunnies Attack)
- [x] fnm
- [x] foretell - available as an ability symbol
- [x] goblinexplosioneers
- [x] golgari - available already
- [x] grandprix (original)
- [x] grandprix (new)
- [x] gruul - available already
- [x] herospath - 1
- [x] herospath - 2
- [x] herospath - 3
- [x] herospath - 4
- [x] herospath - 5
- [x] herospath - 6
- [x] herospath - 7
- [x] herospath - 8
- [x] herospath - 9
- [x] herospath - special
- [x] izzet - available already
- [x] japanjunior
- [x] jeskai - available already
- [x] judgeacademy
- [x] junior
- [x] juniorapac
- [x] junioreurope
- [x] kolaghan - available already
- [x] leagueofdastardlydoom
- [x] lorehold - available already
- [x] maestros
- [x] mardu - available already
- [x] mirran
- [x] cutiemark (apples)
- [x] cutiemark (balloons)
- [x] cutiemark (butterflies)
- [x] cutiemark (gems)
- [x] cutiemark (rainbow)
- [x] cutiemark (sparkle)
- [x] cutiemark (waningmoon) (Nightmare Moon, front)
- [x] cutiemark (waxingmoon) (Princess Luna, back)
- [x] mps - should be in keyrune
- [x] mtg
- [x] mtg10
- [x] mtg15
- [x] nerf
- [x] obscura
- [x] ojutai - available already
- [x] orderofthewidget
- [x] orzhov - available already
- [x] phyrexian - available as phryexian mana symbol
- [x] planeswalker - available as card type
- [x] prismari - available already
- [x] protour
- [x] quandrix - available already
- [x] rakdos - available already
- [x] riveteers
- [x] scholarship
- [x] selesnya - available already
- [x] silumgar - available already
- [x] silverquill - available already
- [x] simic - available already
- [x] sultai - available already
- [x] temur - available already
- [x] transformers
- [x] #114
- [x] witherbloom - available already
- [x] wotc
- [x] wpn

This list excludes all set symbols, which are contained in Keyrune more properly.

#### Excluded

The following watermarks will not be included in Mana as of now, since they're just existing set symbols that certain cards use for various reasons. I'm keeping these separate in Keyrune for now but this is absolutely up for feedback.

* Scars block has the Mirrodin Pure and Phyrexian symbols. Mirrodin Pure is excluded here.
* Wizards of the Coast default shooting star for promos, since this is used as a set symbol. Perhaps this should exist here too though considering how common it is.

---
### Original ticket submitted by @Thom1729:

A number of card watermarks are not implemented.

The majority of these exist only on a handful of promotional cards. The Unstable watermarks, however, are gameplay-relevant, and they appear on Contraptions in icon form.

#### Scars Block

- Mirran
- Phyrexian

#### Unstable

- Agents of S.N.E.A.K.
- Crossbreed Labs
- Goblin Explosioneers
- Legion of Dastardly Doom
- Order of the Widget

#### Promotional

- Arena
- Color Pie (buy-a-box)
- D&D (Hascon)
- DCI
- FNM
- Grand Prix (lands)
- Grand Prix (nonlands)
- Junior Series
- Magic: The Gathering (URL/convention promos)
- Magic 10th Anniversary
- Magic 15th Anniversary
- Magic Scholarship Series
- Nerf (Hascon)
- Pro Tour
- Super Series
- Super Series (APAC)
- Transformers (Hascon)
- Wizards Play Network
- Wizards of the Coast comet thing

#### Other

- Planeswalker (Story Spotlight)
- Set Symbol
- Some Unhinged cards have unique watermarks.

**Comment by MrTeferi** [comment]
@andrewgioia I just noticed a new watermark has arrived 😅 "desparked"
Seen on this card:
https://scryfall.com/card/mat/45/samut-vizier-of-naktamun

**Comment by RivalRowan** [comment]
Oh, I created an .SVG for the despark symbol for the MTG Wiki:
https://mtg.fandom.com/wiki/File:PD.svg

It's traced from:
https://mtgproshop.com/product/mom-march-of-the-machine-despark-tee/

In terms of the other watermarks mentioned. I've got a bunch saved from the old Card Conjurer (prior to it's untimely death).

**Streets of New Capenna**
Brokers: ![family-brokers](https://github.com/andrewgioia/mana/assets/128204978/a5d62c42-97d7-4a46-9ce4-dc9fe54babfd)

Obscura: ![family-obscura](https://github.com/andrewgioia/mana/assets/128204978/c4da55d6-7c81-4159-8470-cb38bec9749c)

Maestros: ![family-maestros](https://github.com/andrewgioia/mana/assets/128204978/d7f26e89-f76f-4656-8eaf-23155a25cd12)

Riveteers: ![family-riveteers](https://github.com/andrewgioia/mana/assets/128204978/b76b5416-607c-4187-89af-d79e772afad4)

Cabaretti: ![family-cabaretti](https://github.com/andrewgioia/mana/assets/128204978/b63dbf02-52dd-4bd6-b03f-4e3d964657d2)

**Unstable**
Agents of S.N.E.A.K: ![faction-agents-of-sneak](https://github.com/andrewgioia/mana/assets/128204978/67a26efa-da74-4a7e-badc-77d3b6fc89c2)

Crossbreed Labs: ![faction-crossbreed-labs](https://github.com/andrewgioia/mana/assets/128204978/80ddb2c6-fe4f-4eb5-848c-1231727325a1)

Goblin Explosioneers: ![faction-goblin-explosioneers](https://github.com/andrewgioia/mana/assets/128204978/996aea67-da99-4016-8003-ee68a6959cb7)

League of Dastardly Doom: ![faction-league-of-dastardly-doom](https://github.com/andrewgioia/mana/assets/128204978/204fc35c-01ce-4c14-800f-70fc32f0e9dd)

Order of the Widget: ![faction-order-of-the-widget](https://github.com/andrewgioia/mana/assets/128204978/3b62b1dd-78a2-4dcc-99c5-d0a3edb0a96f)

**Comment by andrewgioia** [comment]
@RivalRowan amazing, thank you for these!

**Comment by andrewgioia** [comment]
MTG JSON has what seems to be a complete set. After removing all of the set symbols, they list:

- abzan
- agentsofsneak
- arena
- atarka
- azorius
- boros
- brokers
- cabaretti
- colorpie
- conspiracy
- corocoro
- crossbreedlabs
- d&d
- dci
- dengekimaoh
- desparked
- dimir
- dromoka
- flavor
- fnm
- foretell
- goblinexplosioneers
- golgari
- grandprix
- gruul
- herospath
- izzet
- japanjunior
- jeskai
- judgeacademy
- junior
- juniorapac
- junioreurope
- kolaghan
- leagueofdastardlydoom
- lorehold
- maestros
- mardu
- mirran
- mlpgems
- mlpsparkle
- mlpwaningmoon
- mps
- mtg
- mtg10
- mtg15
- nerf
- obscura
- ojutai
- orderofthewidget
- orzhov
- phyrexian
- planeswalker
- prismari
- protour
- quandrix
- rakdos
- riveteers
- scholarship
- selesnya
- silumgar
- silverquill
- simic
- sultai
- tarkir
- temur
- transformers
- trumpkatsumai
- witherbloom
- wotc
- wpn

I'll vet this list with the above and make sure there's complete coverage here.

**Comment by andrewgioia** [comment]
Checking off #113 and #114 here as they've been moved to their own issue

**Comment by andrewgioia** [comment]
Added in v1.16.0

**Comment by andrewgioia** [comment]
Merged into master and closing out this monster issue!
