### ISSUE TITLE
Inaccuracy in documentation (trivial).

### ISSUE THREAD

**Issue by Thom1729** [andrewgioia/Mana#36]
The documentation for "Half Mana Casting Costs" says:

> Even though there's only been one of these ever printed you can still create them :P

However, two cards have half mana symbols: Little Girl (linked in the documentation), and [Mons's Goblin Waiters](https://scryfall.com/card/unh/82/monss-goblin-waiters), which has an ability that adds {HR}.

**Comment by andrewgioia** [comment]
Fixed in 1.6.0
