### ISSUE TITLE
Add editing instructions

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/mana#38]
I'm trying to create a fork of this project for the purposes of adding support for a custom Magic set to [Lore Seeker](https://github.com/fenhl/lore-seeker) which introduces a new mana symbol. However, I haven't worked with SVG fonts yet and am at a complete loss about where to start. Having instructions (or a link to instructions) in the readme would be very useful!

**Comment by gbartholomeu** [comment]
Hi @fenhl , I know andrew already answered but if you need some help ping me. I recently created some fonts for my project and it although it looks weird at first, andrew provided some really good information on how to create a new symbol. Basically you need to: Draw the font, create SVG, import to SVG 'manager' (such as IcoMoon suggest by andrew and it's the same one I used to add compatibility to the original source).

**Comment by andrewgioia** [comment]
Thanks @gbartholomeu! I'm going to close this for now as I intend to overhaul the docs in the v2 release and this will naturally be a part of that.
