### ISSUE TITLE
Counter Icons 

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/mana#39]
We got a bunch counter icons in that article: https://magic.wizards.com/en/articles/archive/magic-online/counter-development-2018-09-05

I think that would be a cool addition.

**Comment by andrewgioia** [comment]
Current status of MODO counterds:

- [ ] Plus
- [ ] Minus
- [ ] Plus uneven (+1/+2, +1/+0, +2/+2, +0/+1)
- [ ] Minus uneven
- [ ] Paw (Egg, Hatchling, Hoofprint Prey, Shell)
- [ ] Skull (Credit, Theft, Wage, Bounty, Hit)
- [ ] Flame (Flame, Fury, Fuse, Shred, Spite, Strife, Blaze)
- [ ] Brick (Brick, Cage, Tower)
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by andrewgioia** [comment]
These are in as of 1.7 just now
