### ISSUE TITLE
Add color indicators

### ISSUE THREAD

**Issue by KingSupernova31** [andrewgioia/mana#40]
Colored dot symbols to display a card's color indicator would be a useful addition. Here's a list of all existing color indicators and a card that uses it:

White: Gideon, Battle-Forged
Blue: Bearer of Overwhelming Truths
Black: Archdemon of Greed
Red: Avacyn, the Purifier
Green: Ancient of the Equinox
Red, Green: Arlinn, Embraced by the Moon
Black, Green: Garruk, the Veil-Cursed
Blue, Black, Red: Nicol Bolas, the Arisen
Red, Green, White: Grimlock, Ferocious King
White, Blue, Black, Red, Green: Transguild Courier

A slight hiccup is that Transguild Courier has never been physically printed with its color indicator, so you'd have to mock one up based on the existing patterns.

**Comment by KingSupernova31** [comment]
Ah, they've already been created here: https://mtg.gamepedia.com/Category:Color_indicators

**Comment by StatiS888** [comment]
@andrewgioia can we expect those indicators for next version?
We decided to include older cards on our website and it is full of them :)

**Comment by andrewgioia** [comment]
@StatiS888 @KingSupernova31 Sorry this took so long! Color indicators are now in v1.10.0 and I updated the docs site to explain how to use them.
