### ISSUE TITLE
Arena keyword icons

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/mana#41]
Arena released icons for various keywords that should be implemented in Mana as they are official symbols.

Reference: https://mtg.gamepedia.com/File:Magic-_The_Gathering_Arena_icons.jpg

Highest res version attahed.

![magic-_the_gathering_arena_icons](https://user-images.githubusercontent.com/221473/52597619-6e400a80-2e21-11e9-9231-47bc22b52df7.jpg)

**Comment by andrewgioia** [comment]
Finally moving on this, the full checklist from https://magicarena.fandom.com/wiki/Abilities is currently:

- [ ] Afflict
- [ ] Aftermath
- [ ] Ascend
- [ ] Convoke
- [ ] Deathtouch
- [ ] Defender
- [ ] Double Strike
- [ ] Enchant
- [ ] Explore
- [ ] Fabricate
- [ ] First Strike
- [ ] Flash
- [ ] Flying
- [ ] Hase
- [ ] Hexproof (Generic)
- [ ] Hexproof (Black)
- [ ] Hexproof (Green)
- [ ] Hexproof (Red)
- [ ] Hexproof (Blue)
- [ ] Hexproof (White)
- [ ] Improvise
- [ ] Indestructible
- [ ] Jumpstart
- [ ] Kicker
- [ ] Lifelink
- [ ] Menace
- [ ] Mentor
- [ ] Prowess
- [ ] Reach
- [ ] Surveil
- [ ] Trample
- [ ] Transform
- [ ] Vigilance

Convenience ability words also used in Arena:

- [ ] Enrage
- [ ] Raid
- [ ] Revolt
- [ ] Undergrowth

The following have a generic bullseye currently: Crew, Cycling, Embalm, Equip, Eternalize

**Comment by andrewgioia** [comment]
A few more from going through Arena:

 - [ ] Escape
 - [ ] Adventure
 - [ ] Summoning Sickness

**Comment by StatiS888** [comment]
1. Some of the keywords in the first list don`t have an icon in the card view or you are putting a generic bullseye icon for them?
(enchant, cycling, kicker, flash, equip, crew)

2. I couldn`t find anywhere in the arena those two keywords - Improvise, Revolt and Fabricate. They are from the sets Aether Revolt and Kaladesh.

3. "The following have a generic bullseye currently: Crew, Cycling, Embalm, Equip, Eternalize"
Embalm and Eternalize have icon in Arena
![embalm+](https://user-images.githubusercontent.com/65974100/91430686-f224e080-e867-11ea-951a-72880f5ec7de.png)

**Comment by Steve-VE** [comment]
>     2. I couldn`t find anywhere in the arena those keywords - Improvise, Revolt and Fabricate. They are from the sets Aether Revolt and Kaladesh.
These sets was on Arena during the beta (and will propably come back one day like Amonkhet did recently).

**Comment by andrewgioia** [comment]
> Some of the keywords in the first list don`t have an icon in the card view or you are putting a generic bullseye icon for them?

Yes for the abilities that have no symbols yet, they'll just be aliases for the generic symbol of that type. The parentheses in that list indicate this, but as an example Enchant has no distinct symbol yet so `.ability-enchant` will just be an alias for `.ability-static`.

> Improvise, Revolt and Fabricate

@Steve-VE is right here, I included them anyway b/c Arena does have symbols for them so it's a little future proofing.

> Embalm and Eternalize have icon in Arena

Thank you! Added to the list and I should have them done today and this v1.8.0 pushed up.

**Comment by StatiS888** [comment]
Thanks for clearing up the .static and .triggered meaning. Then these also need symbols:
![prowess](https://user-images.githubusercontent.com/65974100/91439170-35398080-e875-11ea-905a-3d46c60280bc.png)

**Comment by andrewgioia** [comment]
Wow thanks @StatiS888 I didn't realize there were so many others O_O. 

A few of those look like the existing Guild symbols that we can reuse but there are some distinct ones and 1.8 is probably going to get bumped back a bit. I really appreciate you screenshotting these.

> Are you going to make them in two colors - yellow for non-evergreen and white?

Yeah I can add a convenience class to colorize them that way. The yellow appears to be a gradient.

**Comment by StatiS888** [comment]
found one more - companion. It can only be seen if you start a game though.
![companion](https://user-images.githubusercontent.com/65974100/91975305-dddd5980-ed27-11ea-9f62-11f5cb5b269f.png)

**Comment by andrewgioia** [comment]
These are finally all drawn, hoping to get these in to the next version tomorrow 🤞

**Comment by andrewgioia** [comment]
@Steve-VE @StatiS888 these are all live now in 1.9, I think/hope this is everything but if we're still missing any symbols by all means create new issues and I can add them. Thanks for all your help!

**Comment by StatiS888** [comment]
I tried but couldn't find a way to colorize them, please help.

**Comment by andrewgioia** [comment]
Sorry about that @StatiS888 it looks like I forgot to include that in the main symbol update. v1.9.3 now has a class called `.ms-mechanic` that you can add to the set-specific ability symbols to apply that gold gradient that Arena has.
