### ISSUE TITLE
Loyalty -25 missing

### ISSUE THREAD

**Issue by marshl** [andrewgioia/Mana#42]
Although not a normal card, the oversized Magic 2015 challenge card, _Garruk the Slayer_ (https://scryfall.com/card/ppc1/1/garruk-the-slayer) has a loyalty ability with a cost of "-25", which Mana doesn't have a rule for.

Thanks :)

**Comment by dhouck** [comment]
I know this couldn’t be done with just CSS classes, but it would be nice to be able to in general say something like

```html
<i class="ms ms-loyalty">-25</i>
```
or

```html
<i class="ms ms-cost ms-number">21</i>
```

Or similar things which could let you specify a custom number.

**Comment by andrewgioia** [comment]
Added in 1.6.0
