### ISSUE TITLE
Multicolored symbol

### ISSUE THREAD

**Issue by karsten-mage-market** [andrewgioia/mana#43]
![image](https://user-images.githubusercontent.com/49897734/61856773-17a42580-aec3-11e9-8464-7786c41c820a.png)

https://gamepedia.cursecdn.com/mtgsalvation_gamepedia/3/3e/M.svg

That would be awesome, maybe ms-multicolor

**Comment by StatiS888** [comment]
Can you please add this to 2.0 font?

**Comment by andrewgioia** [comment]
This symbol is obviously pretty basic but it really needs to be 2-tone or else we'll just have a black ring to colorize/style. It's going to require a special class/handling to get this effect.

**Comment by andrewgioia** [comment]
Set for 1.9.1, just adding dual-layered support from keyrune

**Comment by andrewgioia** [comment]
@karsten-mage-market this is now in 1.9.1 and has a new `.ms-duo` optional class (more in the docs on this)
