### ISSUE TITLE
Create a Transform card icon

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#44]
Hello,

First I would like to thank you for such awesome project, now, I want to make a request for a flip icon, for cards with this action, such as:

- Werewolves (Ex: Huntmaster of the fells)
- Artifacts and lands that flips (Example: Primal amulet, Growing Rites of Itlimoc).
- And many other cards that flips.

**Comment by releasethedogs** [comment]
They don't flip.
Flip cards are in Kamigawa block.

You mean "transform".

**Comment by 4eveRS** [comment]
You sir are correct, what I'm trying to request is an icon for the transform mechanic.

Thanks for the correction releasethedogs

**Comment by andrewgioia** [comment]
Added in 1.9!
