### ISSUE TITLE
No mana symbols above 15

### ISSUE THREAD

**Issue by abake-enova** [andrewgioia/Mana#5]
There doesn't currently seem to be any symbols for mana cost of 16 or above. This is only relevant to for a few cards (Draco, Spawnsire of Ulamog), but it would be nice if this was fixed.

**Comment by andrewgioia** [comment]
Wow I didn't realize there were casting costs with numbers that high! I thought Emrakul was the max Thanks I should have this added in shortly!

**Comment by andrewgioia** [comment]
Ok I just cranked it out now actually, [here's the commit](https://github.com/andrewgioia/Mana/commit/9e322328dab1c4674797864d3d0a6b9f390f4155). Thanks again for the request and use!

**Comment by abake-enova** [comment]
Awesome! Thanks, that was quick d:
