### ISSUE TITLE
Issues with small font sizes

### ISSUE THREAD

**Issue by KingSupernova31** [andrewgioia/mana#50]
When the font size is very low, the black portion of the symbol seems to scale down slightly too slowly (and is therefore too big) compared to the colored circle background.

<img width="65" alt="Screen Shot 2020-03-20 at 12 14 41 AM" src="https://user-images.githubusercontent.com/27539004/77135042-20440000-6a40-11ea-93b2-771195f49182.png">

**Comment by andrewgioia** [comment]
Possibly just an issue with split symbols but will investigate why that font size won't scale down.

**Comment by andrewgioia** [comment]
I'm actually not seeing an issue here in Firefox. This is reducing the base cost size in half:

<img width="510" alt="Screen Shot 2023-03-09 at 11 26 18 AM" src="https://user-images.githubusercontent.com/221473/224087900-33886f3d-4b35-43be-bf85-85f72ea33309.png">

@KingSupernova31 would you be able to check if this is still an issue?

**Comment by KingSupernova31** [comment]
Hmm, yeah, not happening for me anymore either. Not sure why.
