### ISSUE TITLE
MTGArena "Rarity" Lotus Icon

### ISSUE THREAD

**Issue by TripleEquals** [andrewgioia/mana#53]
In MTGArena there's a symbol used to represent rarity of cards, and this would be useful as a generic icon for other apps to represent rarity. It comes in a variety of colors that are supposed to represent rarity, but do not really match up with the colors used everywhere else - this ticket is not about that. It would be good to simply have the lotus shape with the standard keyrune colors, example is below, thank you!
![lotusSnip](https://user-images.githubusercontent.com/12373488/90344174-e9145380-dfcb-11ea-93ba-01753ef1dd45.PNG)

**Comment by StatiS888** [comment]
this Icon will be perfect fit for the header above decklists to show the number of cards by rarity.

**Comment by andrewgioia** [comment]
Added in 1.9!
