### ISSUE TITLE
New DFC icons

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/mana#54]
Both can be seen on the helper card.
![Helper_card](https://user-images.githubusercontent.com/25598912/92101947-27887b80-edde-11ea-9da9-5fa0fcff7c29.png)

**Comment by andrewgioia** [comment]
Drawn and set to go up in 1.9.1 soon

**Comment by andrewgioia** [comment]
@yandere-sliver these are in 1.9.1
