### ISSUE TITLE
[DFC] Land MDFC symbol

### ISSUE THREAD

**Issue by StatiS888** [andrewgioia/mana#58]
I know this is exactly as the land symbol but this time the circle is black and the land is white. Moreover the circle has some gradient. I am talking about the land icon symbol on transform cards from XLN set.

We have all the icons for transform cards except this, it would be nice to have it as well.

**Comment by andrewgioia** [comment]
Can most likely reuse the existing land type symbol but will need to make sure

**Comment by andrewgioia** [comment]
![Image](https://user-images.githubusercontent.com/221473/223752148-e07b8533-eb2c-4fe6-a584-411abd1e1b59.png)

**Comment by andrewgioia** [comment]
Added in v1.15.4
