### ISSUE TITLE
[Type] Commander type symbol

### ISSUE THREAD

**Issue by icameron** [andrewgioia/mana#59]
Arena has a commander icon featured in game play and deck construction 

![image](https://user-images.githubusercontent.com/2358801/104807341-231ba700-5843-11eb-9fbc-653c5a786e8e.png)

![image](https://user-images.githubusercontent.com/2358801/104807410-c076db00-5843-11eb-925a-5780215bef99.png)

would be useful to have this in the mana font

**Comment by andrewgioia** [comment]
Added in v1.15.4
