### ISSUE TITLE
[Loyalty] Level Up card text symbol

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#60]
It would be nice to have a level up icon. There are 25 cards that have this ability.

A image for design reference:

![Level_up_3](https://user-images.githubusercontent.com/4212200/106662881-b82bd900-6581-11eb-9070-5e7227ff319f.jpg)

A scryfall list of all leveler cards:

https://scryfall.com/search?q=is%3Aleveler

**Comment by andrewgioia** [comment]
This looks like it could be entirely CSS, will investigate for the 1.16.0 release if not the next point release. If it is just CSS it won't need a glyph, it would just more or less be a convenience class.

**Comment by andrewgioia** [comment]
Added in v1.15.4. This is an initial approach that requires an inner `<span>` element which I hate, I strongly prefer to reduce everything to one element if possible. I'll table this for later though to see if we can handle it better.
