### ISSUE TITLE
Power Toughness Icon

### ISSUE THREAD

**Issue by StatiS888** [andrewgioia/mana#61]
![image](https://user-images.githubusercontent.com/65974100/106723002-51550100-660f-11eb-94ae-8567c6b42a24.png)

it would be nice to have such an icon similar to the planeswalker icons. All creatures use it and it should accept not only integers but * as well.

**Comment by andrewgioia** [comment]
@StatiS888 do you mean the box surrounding the P/T? Looking at it now, it could be done entirely with CSS and doesn't need a glyph per se but just wanted to find out what you're thinking here.

**Comment by andrewgioia** [comment]
Closing for now as I think this is outside the scope
