### ISSUE TITLE
Strixhaven College Symbols

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#63]
Strixhaven will feature 5 colleges, each with a unique symbol.

### Lorehold
![Lorehold](https://user-images.githubusercontent.com/4212200/108468545-a75bb280-7265-11eb-91aa-d6c2a860a5bc.png)

### Prismari
![Prismari](https://user-images.githubusercontent.com/4212200/108468583-b8a4bf00-7265-11eb-924f-91b6aeb422ee.png)

### Quandrix
![Quandrix](https://user-images.githubusercontent.com/4212200/108468603-be9aa000-7265-11eb-896a-3aeebd93103a.png)

### Silverquill
![Silverquill](https://user-images.githubusercontent.com/4212200/108468620-c8240800-7265-11eb-8f5a-cac44ead93e0.png)

### Witherbloom
![Witherbloom](https://user-images.githubusercontent.com/4212200/108468638-d07c4300-7265-11eb-8a4e-5acfb84981f0.png)

**Comment by andrewgioia** [comment]
Thanks @4eveRS, Scryfall drew these SVGs and shared them in Keyrune. I'll transfer that here soon and get them in the next version.

**Comment by andrewgioia** [comment]
Added (with dual-layered support) in 1.14.0
