### ISSUE TITLE
Undefined variable `$ms-ability-grad` in the SASS stylesheet

### ISSUE THREAD

**Issue by mcottret** [andrewgioia/mana#64]
Hi,

First of all thanks for the project, I just started using it & it looks great !

There is an error when trying to `@import` or `@use` the [Mana SASS stylesheet](https://github.com/andrewgioia/mana/blob/master/sass/mana.scss), it seems like the `ms-ability-grad` variable is not defined.

```scss
SassError: Undefined variable.
  ╷
2 │     background: $ms-ability-grad;
  │                 ^^^^^^^^^^^^^^^^
  ╵
```

It is possible to work around this by defining the variable before importing, but adding it with a `!default` would fix the issue & allow to `@use` & override it.

```scss
$ms-ability-grad: linear-gradient(0deg, #c8913b 0%, #ecc65a 100%) !default;
```

Cf https://github.com/andrewgioia/mana/commit/2afc3cab1091a870e023e84b5e1389eb8504c961

Thanks a lot, cheers !

**Comment by andrewgioia** [comment]
Fixed in 1.13.0
