### ISSUE TITLE
`ability-kicker` displays as `ability-static` (SASS only ?)

### ISSUE THREAD

**Issue by mcottret** [andrewgioia/mana#65]
Hi again !

I'm having a strange issue where the `ability-kicker` icon wrongfully displays as the `ability-static` one.

```html
<i class="ms ms-ability-kicker"></i>
```

This seems to be working fine on the documentation page, so this might be specific to the SASS  stylesheet which I am using, if this can help.

Cf https://github.com/andrewgioia/mana/commit/c7cdd21f5669bcfc1a32837ae516452b63a56f67

Also, do you think it would be possible to integrate the "Foretell" ability icon from the latest Kaldheim set ? That would be awesome.

Thanks a lot, cheers !

**Comment by andrewgioia** [comment]
Yep sorry about this @mcottret this is going to be fixed in 1.13 shortly, I forgot to remove kicker from the list with static after kicker got its own symbol.

**Comment by andrewgioia** [comment]
Fixed in 1.13.0
