### ISSUE TITLE
[KHM] Raven

### ISSUE THREAD

**Issue by slecache** [andrewgioia/mana#66]
I didn't found this "raven" icon used as watermark on foretell cards.

![image](https://user-images.githubusercontent.com/9013641/111010023-92220180-8395-11eb-91af-231d5a1d6650.png)

**Comment by andrewgioia** [comment]
Just an FYI this is the same as #68 (foretell) which will go up in the next release

**Comment by andrewgioia** [comment]
Added in 1.11.0
