### ISSUE TITLE
Lesson Icon

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#73]
Lesson sorcery cards introduced on Strixhaven set have an icon similar to those seen on MDFC and Double Faced cards.

Below is and example obtained from Magic Arena:

![lesson_icon](https://user-images.githubusercontent.com/4212200/115768399-a4be2c00-a380-11eb-88e1-298f73f47f09.PNG)

**Comment by andrewgioia** [comment]
Added in 1.11.0
