### ISSUE TITLE
SVG licensing?

### ISSUE THREAD

**Issue by leemi** [andrewgioia/mana#74]
Hi,
I was interesting in using the SVG versions of the icons, but there doesn't seem to be any licensing information for them.

(I came across [this](https://github.com/ForkAwesome/Fork-Awesome/issues/62), and thought this might be helpful in your response)

**Comment by andrewgioia** [comment]
Thanks for that link @leemi and yes I would agree that the extracted SVGs are part of the font and would fall under the SIL OFL 1.1 that the font itself is distributed under.
