### ISSUE TITLE
Loyalty symbol display issues

### ISSUE THREAD

**Issue by KingSupernova31** [andrewgioia/mana#79]
Loyalty symbols don't seem to display properly for me. (Tested on multiple browsers.) The number inside the symbol is rather thin and difficult to read, doesn't look at all like it does on a card.

![image](https://user-images.githubusercontent.com/27539004/127257925-ee205855-2c39-45e4-9871-d7acb07d3ef4.png)

![image](https://user-images.githubusercontent.com/27539004/127258044-8818c98b-b3af-4482-a3a5-35dc91d96e40.png)

**Comment by gbartholomeu** [comment]
Hi @KingSupernova31, how are you using the symbol? Is it the installed font? Css?

**Comment by KingSupernova31** [comment]
Yep, installed as a font, accessing via CSS tags like "<i class='ms ms-gp ms-cost'></i>"

**Comment by gbartholomeu** [comment]
Could try using the size modifier to see if it fits better your needs? 

It should look like `<i class='ms ms-gp ms-cost ms-2x'></i>`

The ranges goes from 2-6.

**Comment by KingSupernova31** [comment]
That just scales the size of the entire symbol, it doesn't address the problem I was pointing out; that the ratio of the character width to the overall symbol width is too low.

It does however look like this problem has been fixed in the mean time, the same line of text now looks like this:
![Screen Shot 2022-12-23 at 15 09 56](https://user-images.githubusercontent.com/27539004/209412427-fc29a868-cd18-41d4-80f6-74b6bf0ce1cb.JPG)
Which is more readable.
