### ISSUE TITLE
A few more symbols missing

### ISSUE THREAD

**Issue by erg** [andrewgioia/Mana#8]
From this link, you can see there are a few more weird symbols from random cards:
http://www.slightlymagic.net/forum/viewtopic.php?t=4430

Infinity and 100:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74323

1,000,000 mana:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=73947

That might be all?

**Comment by andrewgioia** [comment]
Great, I just pushed up changes for the 100 and 1,000,000 symbols. 1/2 and infinite also need to be done according to that screenshot.

**Comment by andrewgioia** [comment]
Ok the 1/2 and infinity should be good to go now too
