### ISSUE TITLE
Conflict with bootstrap 5

### ISSUE THREAD

**Issue by dginio** [andrewgioia/mana#80]
Hello,

Since Bootstrap 5 the margin shortcuts has changed, they replace left and right with start and end.
https://getbootstrap.com/docs/5.0/utilities/spacing/
ml-1 (margin left 1em) is now ms-1 (margin start)

all ms-<number> can't be used.

Do you have an idea for a workaround ?

Thanks

**Comment by andrewgioia** [comment]
Hi @dginio I'm sorry I haven't gotten back to you sooner and that this conflicts with their spacing utility classes.

We can't change the prefix default but you can absolutely do this if you build the CSS files yourself. Using Sass, this would mean overwriting the variable `$ms-prefix` which is defined in [variables.scss](https://github.com/andrewgioia/mana/blob/master/sass/_variables.scss). That variable has a [default flag](https://sass-lang.com/documentation/variables#default-values) which means if you set it first, Mana will not set it to `ms-`.
