### ISSUE TITLE
Magic Duels Ability Icons

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#85]
I just found out about [Magic Duels ability icons](https://magicduels.fandom.com/wiki/Abilities), below is the image of the complete list of icons:

![image](https://user-images.githubusercontent.com/4212200/143302450-cac73dec-646b-405e-b5b4-de38233acc30.png)

The relation between the ability icon and row/column:

- R1C1: Protection from White
- R1C2: Protection from Blue
- R1C3: Protection from Black
- R1C4: Protection from Red
- R1C5: Protection from Green
- R1C6: Reach
- R1C7: Hexproof
- R2C1: Haunt
- R2C2: Vigilance
- R2C3: Trample
- R2C4: Deathtouch
- R2C5: Indestructible
- R2C6: Totem Armor
- R2C7: Lifelink
- R3C1: Can't Untap
- R3C2: Legendary
- R3C3: Intimidate
- R3C4: First Strike
- R3C5: Double Strike
- R3C6: Haste
- R3C7: Fear
- R4C1: Annihilator
- R4C2: Prevent Damage
- R4C3: Defender
- R4C4: Infect
- R4C5: Flying
- R4C6: Battle Cry
- R4C7: Copy
- R5C1: Regeneration
- R5C2: Shroud
- R5C3: Plainswalk
- R5C4: Islandwalk
- R5C5: Swampwalk
- R5C6: Mountainwalk
- R5C7: Forestwalk

Some of these icons were updated for Magic Arena, while others are the same.

I think it would be a nice addition to this project.

**Comment by nicochulo2001** [comment]
I believe some of the labels are erroneous. I haven't used the Duels client at any point, yet there's a few incongruencies I've found:
- R5C2 is labelled as Shroud yet in the Wiki article it says that it's Hexproof

**Comment by nicochulo2001** [comment]
I believe some of the labels are erroneous. I haven't used the Duels client at any point, yet there's a few incongruencies I've found:
- R1C6 is labelled as Hexproof yet in the Wiki it says it's Regeneration
- R2C1 is labelled as Haunt yet in the Magic Arena Wiki (that showcases some of the old Duels icons) it is labelled as Menace. Worth noting Menace is given a totally different icon in the Duels Wiki, so this one's dubious
- R5C1 is labelled as Regeneration yet the icon for Regeneration is in R1C6 (according to the Duels Wiki)
- R5C2 is labelled as Shroud yet in the Wiki it says that it's Hexproof

Here's the link for the [Magic Duels article about abilities](https://magicduels.fandom.com/wiki/Abilities) and here's the Magic Arena Wiki icon list:
![image](https://user-images.githubusercontent.com/44652077/164911542-a2d064bd-4020-48f9-a037-fc38de65797b.png)

**Comment by nicochulo2001** [comment]
I also dug deeper and found [a bizarre Xbox article about Duels](https://dlassets-ssl.xboxlive.com/public/content/4cf7c73f-39d2-4903-b1c1-c9354e636835/GameManual/3994073f-6277-4dba-bf63-36bbe2558062/en-US/index.html#article_abilities) that showcases a few additional icons:
![Detain](https://user-images.githubusercontent.com/44652077/164916606-dcb147a7-af8b-47e7-b5eb-402598ebdfd9.png)
Detain
![Evolve](https://user-images.githubusercontent.com/44652077/164916621-e5866eb3-ec69-439b-9be7-09e7cd302156.png)
Evolve
![Exalted](https://user-images.githubusercontent.com/44652077/164916626-431d7ad8-2d5e-4733-942e-6787c7ff3c54.png)
Exalted
![Fading](https://user-images.githubusercontent.com/44652077/164916631-e7b04e4f-80b0-4447-8606-44a1a2854a6a.png)
Fading
![Menace](https://user-images.githubusercontent.com/44652077/164916633-0c54ccb0-efa4-4cde-a70d-da469a51aa6f.png)
Menace
![Monstrous](https://user-images.githubusercontent.com/44652077/164916637-09ac3414-b891-4867-a9dd-177174d8e848.png)
Monstrosity (Monstrous)
![Protection_Generic](https://user-images.githubusercontent.com/44652077/164916665-7a063248-c187-4594-8c61-a3494df59c0c.png)
Protection
![Renown](https://user-images.githubusercontent.com/44652077/164916671-53bb0b2b-7adf-4d8e-bce8-0fba55d6f880.png)
Renown (Renowned)
![Soulshift](https://user-images.githubusercontent.com/44652077/164916681-e7a4dd73-4d43-4aa4-9baf-0336f7bd2175.png)
Soulshift
![Undying](https://user-images.githubusercontent.com/44652077/164916684-71cd8897-7aa2-46f1-ac6f-9831d46cd28b.png)
Undying

**Comment by andrewgioia** [comment]
@4eveRS this is amazing and I'm sorry I'm just seeing this issue now. I agree these would be a great addition and help complete Mana.

I'll have to dig into this this week and see if there might be anything else missing but this looks complete.

**Comment by andrewgioia** [comment]
This one got moved yet again, to v1.17.1, which I hope to have out shortly now. Didn't want to hold up the big 2024 release with this other big one but I will get these in.

**Comment by andrewgioia** [comment]
> I believe some of the labels are erroneous. I haven't used the Duels client at any point, yet there's a few incongruencies I've found:
> 
>     * R1C6 is labelled as Hexproof yet in the Wiki it says it's Regeneration
> 
>     * R5C1 is labelled as Regeneration yet the icon for Regeneration is in R1C6 (according to the Duels Wiki)
> 
>     * R5C2 is labelled as Shroud yet in the Wiki it says that it's Hexproof

Thank you for going through these, just a few clarifications as I move forward on this thing finally:

* R1C7 (not C6, just fyi) is labeled as Hexproof but you're right, that's Regeneration
* R5C2 is Hexproof instead, not Shroud.
* R5C1 is not Regeneration and doesn't seem to be labeled anywhere, maybe this is Shroud? I think I'll assume this for now.

That leaves the following list, which includes the additional Xbox screenshots as well as the ones from the Wiki screengrab not present here:

Row 1
- [ ] Protection from White
- [ ] Protection from Blue
- [ ] Protection from Black
- [ ] Protection from Red
- [ ] Protection from Green
- [ ] Reach
- [ ] Regneration

Row 2
- [ ] Haunt
- [ ] Vigilance
- [ ] Trample
- [ ] Deathtouch
- [ ] Indestructible
- [ ] Totem Armor
- [ ] Lifelink

Row 3
- [ ] Can't Untap
- [ ] Legendary
- [ ] Intimidate
- [ ] First Strike
- [ ] Double Strike
- [ ] Haste
- [ ] Fear

Row 4
- [ ] Annihilator
- [ ] Prevent Damage
- [ ] Defender
- [ ] Infect
- [ ] Flying
- [ ] Battle Cry
- [ ] Copy

Row 5
- [ ] Shroud
- [ ] Hexproof
- [ ] Plainswalk
- [ ] Islandwalk
- [ ] Swampwalk
- [ ] Mountainwalk
- [ ] Forestwalk

Xbox
- [ ] Skulk
- [ ] Delirium
- [ ] Cohort
- [ ] Ingest
- [ ] Rally
- [ ] Temporary Control
- [ ] Must Attack
- [ ] DFC
- [ ] Doesn't Untap
- [ ] Can't Block
- [ ] Can't Be Blocked
- [ ] Exile
- [ ] Detain
- [ ] Evolve
- [ ] Exalted
- [ ] Fading
- [ ] Menace
- [ ] Monstrous
- [ ] Protection
- [ ] Renowned
- [ ] Soulshift
- [ ] Undying

Fun!

**Comment by andrewgioia** [comment]
Closing this one as all are now in v1.18.0! Woohoo!
