### ISSUE TITLE
Add New hybrid Phyrexian mana

### ISSUE THREAD

**Issue by icameron** [andrewgioia/mana#86]
Please add the New hybrid Phyrexian mana symbols scryfall has created them 

https://github.com/scryfall/manamoji-discord/commit/07424d083f1617b65516a2cfcd466e4b9701a033

**Comment by BarneyL01** [comment]
I was able to achieve this by adding this to my own CSS for the after phyrexian symbol, and using the ms-split
```css
.ms-pp::after {
  content: "\e618";
}
```

So for [Tamiyo, Compleated Sage](https://scryfall.com/card/neo/238/tamiyo-compleated-sage) the hybrid phrexian symbol is:
```html
<i class="ms ms-cost ms-shadow ms-p ms-split ms-pp ms-ci-gu"></i>
```

**Comment by gbartholomeu** [comment]
In case @BarneyL01 's answer is not enough, you can check out my css https://github.com/gbartholomeu/mtg-minimalist-proxies/blob/master/minimalistproxies/html/css/mana.css 

I created all hybrid manas following the pattern ms- so:

- .ms-bgp
- .ms-brp
- .ms-gup
- .ms-gwp
- .ms-rgp
- .ms-rwp
- .ms-ubp
- .ms-urp
- .ms-wbp
- .ms-wup

you can use it as the original hybrid manas: `ms ms-cost ms-wup`

**Comment by andrewgioia** [comment]
Thanks @gbartholomeu, adding this in 1.15.3 shortly

**Comment by andrewgioia** [comment]
Added in 1.15.3
