### ISSUE TITLE
Internal font file name doesnt not equal css font-family name

### ISSUE THREAD

**Issue by Ecredes** [andrewgioia/mana#87]
Thanks for this project, it's great.  I'm using this in a somewhat special scenario- embedded in ebook EPUB3 files. (works great in this type of application by the way).  

There is one exception that comes up when finalizing the epub files, where the CSS font-family name does not match the internal font file name, and that this may cause some issues with some e-reader devices. (I have not encountered any issue myself, this is just a warning that comes up)

Example:
@font-face {
  src: url(../fonts/mana.ttf);
  font-family: "Mana";
  font-weight: normal;
  font-style: normal;
}

inside the font file, the font name is 'mana' (all lowercase).

Seems like an easy fix, to make these the same name in future releases. And will avoid any potential issue in for this type of use case in the future.

**Comment by andrewgioia** [comment]
The next font build in 1.15.4 will contain this fix, it just required an update in the font compiler (Icomoon)

**Comment by andrewgioia** [comment]
Added in v1.15.4
