### ISSUE TITLE
Shield Counters from Arena?

### ISSUE THREAD

**Issue by JustAMalcontent** [andrewgioia/mana#90]
Is there any possibility of including an icon for Shield Counters?

**Comment by ThePieBandit** [comment]
+1

**Comment by andrewgioia** [comment]
Yes absolutely @JustAMalcontent I need to get a full list of all of the new ability icons and counters that have been added to Arena and MODO since the last update 😬

**Comment by ThePieBandit** [comment]
Duplicate of #94 at this point since all the tracking is done there?
