### ISSUE TITLE
[REQUEST] Unfinity Tickets Counter

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#92]
Ticket counter introduced in Unfinity. (more about [here](https://mtg.fandom.com/wiki/Ticket_counter)).

![ticket](https://user-images.githubusercontent.com/4212200/180855841-2894320a-6ce8-49fc-852f-378c8f1eccfc.PNG)
Example _(sorry for the small pic./bad quality)_

Icon code (used in Scryfall): {TK}

**Comment by KingSupernova31** [comment]
Should be TK, not TIX. TK is the official symbol code defined by WIzards, and Scryfall now appears to use it too.

https://scryfall.com/search?q=o%3A%7BTK%7D&unique=cards&as=grid&order=name

**Comment by andrewgioia** [comment]
Does anyone have a higher resolution version of this symbol? A quick search can't find anything but just wondering if you all see anything.

**Comment by 4eveRS** [comment]
![image](https://user-images.githubusercontent.com/4212200/222795124-30f36319-b212-4cc7-a7b4-6f0512507018.png)

**Comment by andrewgioia** [comment]
Amazing! Thank you @4eveRS

**Comment by andrewgioia** [comment]
Added in 1.15.1
