### ISSUE TITLE
Loyalty symbols with 2 digit numbers have inconsistent text vertical position

### ISSUE THREAD

**Issue by KingSupernova31** [andrewgioia/mana#96]
Some loyalty symbols have text that's too low, running off the edge of the symbol.
![Screen Shot 2022-12-24 at 10 08 10](https://user-images.githubusercontent.com/27539004/209447111-760eafed-af68-47ef-b2fa-08891aaf0b44.JPG)

Strangely, the text position differs between different symbols. 10, 12, and 14 are all at the same vertical position as the single digit numbers, which works fine for single digits, but runs off the edge once it's two digits. 11, 13, and 15 however have the number shifted up slightly so that they're properly centered in the box.
![Screen Shot 2022-12-24 at 10 08 03](https://user-images.githubusercontent.com/27539004/209447202-bc12e308-ede8-49a5-aa27-c0144ce1589c.JPG)

**Comment by andrewgioia** [comment]
Added in 1.15.5
