### ISSUE TITLE
Outlined Planeswalker loyalty symbol

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/mana#97]
Hello @andrewgioia!

Some cards added a planeswalker loyalty symbol on their oracle text, when they appear on oracle text it's displayed in an outlined style. I'm here again requesting a new icon 😆

Example:
![unf-166-comet-stellar-pup](https://user-images.githubusercontent.com/4212200/218839253-602f04c5-f108-4a84-babb-c097fc0e25ac.jpg)

**Comment by andrewgioia** [comment]
Will go into 1.15.1 after this major update currently
