### ISSUE TITLE
[DFC] Kamigawa MDFC Saga symbol

### ISSUE THREAD

**Issue by MrTeferi** [andrewgioia/mana#98]
Kamigawa introduced MDFC Saga's with a fan closed and fan open symbol in the transform symbol slot, would very much like to add these to Mana! Here are examples:

FAN OPEN - [SVG](https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/2/27/Dfc-openfan.svg)
![image](https://user-images.githubusercontent.com/92750180/219710085-8ad65b58-eb35-456f-87e8-f8e8d7c1ccd2.png)

FAN CLOSED - [SVG](https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/4/47/Dfc-closedfan.svg)
![image](https://user-images.githubusercontent.com/92750180/219710168-29df199e-4a94-4d97-b071-67ba4ee35a43.png)

**Comment by MrTeferi** [comment]
Also an example card for reference:
![image](https://user-images.githubusercontent.com/92750180/219710454-7f33256e-8128-45be-a907-7819d34a3825.png)

**Comment by andrewgioia** [comment]
Will go into 1.15.1 after this current major update

**Comment by MrTeferi** [comment]
> Will go into 1.15.1 after this current major update

@andrewgioia Thanks buddy! Also I apologize for the duplicate issue post I just saw that I already posted an issue back in March of 22 about this symbol I completely forgot about that and never followed up with the appropriate SVG links, has been a busy year haha

**Comment by andrewgioia** [comment]
Sure thing @MrTeferi and not your fault at all, I let way too much time go by before getting into these issues.

I forgot to add this in the previous point releases but should have it up soon.

**Comment by andrewgioia** [comment]
Added in 1.15.5
